"use client"

import { useEffect, useMemo, useState } from "react"
import { Loader2, Search, Save } from "lucide-react"
import { auth } from "@/lib/firebase"
import { Button } from "@/components/ui/button"

type AdminUser = { uid: string; mvbdId?: string; name?: string; email?: string; accessType?: string | null; subscriptionStatus?: string | null; subscriptionPlan?: string | null }

export default function AdminUsersLive() {
  const [users, setUsers] = useState<AdminUser[]>([])
  const [query, setQuery] = useState("")
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState<string | null>(null)
  const [error, setError] = useState("")
  useEffect(() => { void (async () => { try { if (!auth.currentUser) throw new Error("Sign in with an admin account to manage users."); const token = await auth.currentUser.getIdToken(); const response = await fetch("/api/admin/users", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setUsers(body) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to load users.") } finally { setLoading(false) } })() }, [])
  const filtered = useMemo(() => users.filter((user) => `${user.name} ${user.email} ${user.mvbdId}`.toLowerCase().includes(query.toLowerCase())), [query, users])
  const update = async (user: AdminUser) => { if (!auth.currentUser) return; setSaving(user.uid); try { const token = await auth.currentUser.getIdToken(); const response = await fetch("/api/admin/users", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ uid: user.uid, name: user.name, accessType: user.accessType || null, subscriptionStatus: user.subscriptionStatus || null }) }); if (!response.ok) throw new Error((await response.json()).error); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Update failed.") } finally { setSaving(null) } }
  return <div className="rounded-2xl border border-white/8 bg-card"><div className="flex flex-col gap-4 border-b border-white/8 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-semibold">Users</h2><p className="mt-1 text-xs text-muted-foreground">Edit profile and access status directly from Firestore</p></div><div className="relative w-full md:w-72"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search users..." className="h-9 w-full rounded-lg border border-white/10 bg-secondary/50 pl-9 pr-3 text-sm outline-none" /></div></div>{error && <p className="m-5 rounded-xl bg-rose-400/10 p-3 text-sm text-rose-200">{error}</p>}{loading ? <div className="flex items-center gap-2 p-5 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading users...</div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="border-b border-white/8 text-xs text-muted-foreground"><tr><th className="px-5 py-3">User</th><th className="px-5 py-3">Access</th><th className="px-5 py-3">Status</th><th className="px-5 py-3" /></tr></thead><tbody>{filtered.map((user) => <tr key={user.uid} className="border-b border-white/6"><td className="px-5 py-4"><input value={user.name || ""} onChange={(event) => setUsers((current) => current.map((item) => item.uid === user.uid ? { ...item, name: event.target.value } : item))} className="mb-1 block w-full rounded bg-secondary/50 px-2 py-1 font-medium outline-none" /><div className="text-xs text-muted-foreground">{user.email} · {user.mvbdId}</div></td><td className="px-5 py-4"><select value={user.accessType || ""} onChange={(event) => setUsers((current) => current.map((item) => item.uid === user.uid ? { ...item, accessType: event.target.value || null } : item))} className="rounded bg-secondary px-2 py-1"><option value="">None</option><option value="trial">Trial</option><option value="subscription">Subscription</option></select></td><td className="px-5 py-4"><select value={user.subscriptionStatus || ""} onChange={(event) => setUsers((current) => current.map((item) => item.uid === user.uid ? { ...item, subscriptionStatus: event.target.value || null } : item))} className="rounded bg-secondary px-2 py-1"><option value="">Inactive</option><option value="active">Active</option><option value="pending">Pending</option><option value="expired">Expired</option></select></td><td className="px-5 py-4"><Button size="sm" disabled={saving === user.uid} onClick={() => void update(user)}><Save data-icon="inline-start" />Save</Button></td></tr>)}</tbody></table></div>}</div>
}
