export interface Anime {
  id: number
  title: string
  poster: string
  trailer: string
  telegramLink: string
  genre: string
  year: string
  rating: string
  language: string
  description: string
  views: number
}

export const animes: Anime[] = [
  {
    id: 1,
    title: "Spirited Away",
    poster: "/1id.jpg",
    trailer: "https://www.youtube.com/embed/aL-97TEa43Y?si",
    telegramLink: "https://t.me/animeversebd/9",
    genre: "Action | Drama | Thriller",
    year: "2001",
    rating: "9.1",
    language: "Hindi",
    description: "A magical journey to a spirit world beyond imagination.",
    views: 1250,
  },
  {
    id: 2,
    title: "The Monkey King",
    poster: "/2id.jpg",
    trailer: "https://www.youtube.com/embed/0pmIANSKkdo?si",
    telegramLink: "https://t.me/animeverse_bd",
    genre: "Action | Supernatural | Historical",
    year: "2023",
    rating: "5.6",
    language: "Hindi",
    description: "এক কিংবদন্তীর শুরু, এক অসাধারণ অভিযান।",
    views: 2340,
  },
  {
    id: 3,
    title: "Your Name",
    poster: "/3id.jpg",
    trailer: "https://www.youtube.com/embed/_oWzYOwXn-o?si",
    telegramLink: "https://t.me/animeversebd/13",
    genre: "Action | School | Supernatural",
    year: "2016",
    rating: "8.4",
    language: "Hindi",
    description: "দুই হৃদয়ের অলৌকিক গল্প, যা সময় ও দূরত্বকে ছাপিয়ে যায়।",
    views: 3450,
  },
  {
    id: 4,
    title: "A Whisker Away",
    poster: "/4id.jpg",
    trailer: "https://www.youtube.com/embed/zGGp2RVoPdU?si",
    telegramLink: "https://t.me/animeversebd/17",
    genre: "Adventure | Comedy | Action",
    year: "2020",
    rating: "6.7",
    language: "Hindi",
    description: "A magical adventure with unexpected twists.",
    views: 1890,
  },
  {
    id: 5,
    title: "Drifting Home",
    poster: "/5id.jpg",
    trailer: "https://www.youtube.com/embed/zY5O9JRPKLY?si",
    telegramLink: "https://t.me/animeversebd/19",
    genre: "Action | Martial Arts | Adventure",
    year: "2022",
    rating: "6.5",
    language: "Hindi",
    description: "A heartwarming story of friendship and adventure.",
    views: 1567,
  },
  {
    id: 6,
    title: "Once Upon a Witch's Death Season 1",
    poster: "/6id.jpg",
    trailer: "https://www.youtube.com/embed/FerOCv5eOHI?si",
    telegramLink: "https://t.me/animeversebd/21",
    genre: "Action | Adventure | Martial Arts",
    year: "2025",
    rating: "8.7",
    language: "Hindi",
    description: "A thrilling tale of magic and mystery.",
    views: 2100,
  },
  {
    id: 7,
    title: "A Great Cleric Season 1",
    poster: "/7id.jpg",
    trailer: "https://www.youtube.com/embed/susqUMviH_E?si",
    telegramLink: "https://t.me/animeversebd/46",
    genre: "Superhero | School | Action",
    year: "2023",
    rating: "7.5",
    language: "Hindi",
    description: "An epic journey of a powerful cleric.",
    views: 1750,
  },
  {
    id: 8,
    title: "Rurouni Kenshin Season 1",
    poster: "/8id.jpg",
    trailer: "https://www.youtube.com/embed/ZONOltoCdP4?si",
    telegramLink: "https://t.me/animeversebd/73",
    genre: "Thriller | Supernatural | Psychological",
    year: "2023",
    rating: "7.9",
    language: "Hindi",
    description: "A legendary swordsman's journey through time.",
    views: 1900,
  },
  {
    id: 9,
    title: "A Couple of Cuckoos Season 1",
    poster: "/9id.jpg",
    trailer: "https://www.youtube.com/embed/WtBwfWvUEqY?si",
    telegramLink: "https://t.me/animeversebd/82",
    genre: "Comedy | Action | Supernatural",
    year: "2022",
    rating: "7.1",
    language: "Hindi",
    description: "A hilarious romantic comedy with supernatural elements.",
    views: 1600,
  },
  {
    id: 10,
    title: "The Misfit of Demon King Academy Season 1",
    poster: "/10id.jpg",
    trailer: "https://www.youtube.com/embed/e8YBesRKq_U?si",
    telegramLink: "https://t.me/animeversebd/137",
    genre: "Action | Supernatural | Adventure",
    year: "2020",
    rating: "7.3",
    language: "Hindi",
    description: "A powerful demon king returns to his academy.",
    views: 1800,
  },
  {
    id: 11,
    title: "Shangri La Frontier Season 2",
    poster: "/11id.jpg",
    trailer: "https://www.youtube.com/embed/R_7Okd4X1lU?si",
    telegramLink: "https://t.me/animeversebd/193",
    genre: "Action | Adventure | Fantasy | Game",
    year: "2025",
    rating: "8.6",
    language: "Hindi",
    description: "An epic gaming adventure continues.",
    views: 2200,
  },
  {
    id: 12,
    title: "Attack on Titan Season 1",
    poster: "/12id.jpg",
    trailer: "https://www.youtube.com/embed/LajOXSdyBeE?si",
    telegramLink: "https://t.me/animeversebd/198",
    genre: "Action | Supernatural | Adventure",
    year: "2013",
    rating: "9.0",
    language: "Hindi",
    description: "Humanity fights for survival against giant titans.",
    views: 2500,
  },
  {
    id: 13,
    title: "Attack on Titan Season 2",
    poster: "/13id.jpg",
    trailer: "https://www.youtube.com/embed/X2WGyFRKb8Y?si",
    telegramLink: "https://t.me/animeversebd/250",
    genre: "Action | Supernatural | Adventure",
    year: "2017",
    rating: "8.9",
    language: "Hindi",
    description: "The battle against titans intensifies.",
    views: 2400,
  },
  {
    id: 14,
    title: "Attack on Titan Season 3",
    poster: "/14id.jpg",
    trailer: "https://www.youtube.com/embed/mBGyz4G60cQ?si",
    telegramLink: "https://t.me/animeversebd/273",
    genre: "Action | Supernatural | Adventure",
    year: "2018",
    rating: "9.2",
    language: "Hindi",
    description: "Secrets of the titans are revealed.",
    views: 2600,
  },
  {
    id: 15,
    title: "Attack on Titan Season 4",
    poster: "/15id.jpg",
    trailer: "https://www.youtube.com/embed/cR0zTG2czV0?si",
    telegramLink: "https://t.me/animeversebd/318",
    genre: "Action | Supernatural | Adventure",
    year: "2020",
    rating: "9.3",
    language: "Hindi",
    description: "The final season brings epic conclusions.",
    views: 2700,
  },
  {
    id: 16,
    title: "Olaf Presents Season 1",
    poster: "/16id.jpg",
    trailer: "https://www.youtube.com/embed/2Stzk2aopxs?si",
    telegramLink: "https://t.me/animeversebd/376",
    genre: "Animation | Comedy | Short",
    year: "2021",
    rating: "7.3",
    language: "English",
    description: "Olaf presents hilarious Disney stories.",
    views: 1700,
  },
  {
    id: 17,
    title: "Brave",
    poster: "/17id.jpg",
    trailer: "https://www.youtube.com/embed/fyP0IGEzr4s?si",
    telegramLink: "https://t.me/animeversebd/389",
    genre: "Animation | Adventure | Fantasy",
    year: "2012",
    rating: "7.1",
    language: "English",
    description: "A brave princess fights for her destiny.",
    views: 1650,
  },
  {
    id: 18,
    title: "DC League of Super-Pets",
    poster: "/18id.jpg",
    trailer: "https://www.youtube.com/embed/dgtFO6ANznY?si",
    telegramLink: "https://t.me/animeversebd/391",
    genre: "Animation | Action | Comedy",
    year: "2022",
    rating: "7.2",
    language: "English/Hindi",
    description: "Superhero pets save the day.",
    views: 1750,
  },
  {
    id: 19,
    title: "Doraemon: Nobita's Chronicle of the Moon Exploration",
    poster: "/19id.jpg",
    trailer: "https://www.youtube.com/embed/w7Iz-zsltjw?si",
    telegramLink: "https://t.me/animeversebd/393",
    genre: "Animation | Sci-Fi | Adventure",
    year: "2019",
    rating: "6.7",
    language: "Hindi",
    description: "Doraemon and Nobita explore the moon.",
    views: 1550,
  },
  {
    id: 20,
    title: "Justice Society: World War II",
    poster: "/20id.jpg",
    trailer: "https://www.youtube.com/embed/qx2zoSk42BI?si",
    telegramLink: "https://t.me/animeversebd/395",
    genre: "Animation | Action | Superhero",
    year: "2021",
    rating: "6.4",
    language: "Hindi",
    description: "Superheroes fight in World War II.",
    views: 1450,
  },
  {
    id: 21,
    title: "Puss in Boots: The Last Wish",
    poster: "/21id.jpg",
    trailer: "https://www.youtube.com/embed/tsTLlZ32SpI?si",
    telegramLink: "https://t.me/animeversebd/397",
    genre: "Animation | Adventure | Comedy",
    year: "2022",
    rating: "7.8",
    language: "Hindi",
    description: "Puss in Boots goes on one last adventure.",
    views: 1850,
  },
  {
    id: 22,
    title: "Constantine: City of Demons",
    poster: "/22id.jpg",
    trailer: "https://www.youtube.com/embed/6vL--ZrHC6U?si",
    telegramLink: "https://t.me/animeversebd/399",
    genre: "Animation | Action | Fantasy",
    year: "2018",
    rating: "7.4",
    language: "English/Hindi",
    description: "Constantine battles demons in the city.",
    views: 1750,
  },
  {
    id: 23,
    title: "Doraemon: Nobita and the Kingdom of Clouds",
    poster: "/23id.jpg",
    trailer: "https://www.youtube.com/embed/6ndjhJo2zFw?si",
    telegramLink: "https://t.me/animeversebd/401",
    genre: "Animation | Adventure | Family",
    year: "1992",
    rating: "7.0",
    language: "Hindi",
    description: "Doraemon and friends discover a cloud kingdom.",
    views: 1600,
  },
  {
    id: 24,
    title: "Hotel Transylvania 2",
    poster: "/24id.jpg",
    trailer: "https://www.youtube.com/embed/E3mL9H3C2OY?si",
    telegramLink: "https://t.me/animeversebd/403",
    genre: "Animation | Comedy | Family",
    year: "2015",
    rating: "6.6",
    language: "English/Hindi",
    description: "Dracula's family returns for more fun.",
    views: 1500,
  },
  {
    id: 25,
    title: "Hotel Transylvania 3: Summer Vacation",
    poster: "/25id.jpg",
    trailer: "https://www.youtube.com/embed/Qvt0KnhtPBk?si",
    telegramLink: "https://t.me/animeversebd/405",
    genre: "Animation | Comedy | Family",
    year: "2018",
    rating: "6.3",
    language: "Hindi",
    description: "Dracula goes on a summer vacation.",
    views: 1400,
  },
  {
    id: 26,
    title: "Ainbo: Spirit of the Amazon",
    poster: "/26id.jpg",
    trailer: "https://www.youtube.com/embed/PWRtf3pc14c?si",
    telegramLink: "https://t.me/animeversebd/407",
    genre: "Animation | Adventure | Fantasy",
    year: "2021",
    rating: "4.8",
    language: "Hindi",
    description: "A girl protects the Amazon rainforest.",
    views: 1200,
  },
  {
    id: 27,
    title: "Onward",
    poster: "/27id.jpg",
    trailer: "https://www.youtube.com/embed/dLXt8r1cQVk?si",
    telegramLink: "https://t.me/animeversebd/409",
    genre: "Animation | Adventure | Comedy",
    year: "2020",
    rating: "7.4",
    language: "Hindi",
    description: "Two brothers go on a magical quest.",
    views: 1700,
  },
  {
    id: 28,
    title: "Zootopia",
    poster: "/28id.jpg",
    trailer: "https://www.youtube.com/embed/X4XvU9FT0NM?si",
    telegramLink: "https://t.me/animeversebd/411",
    genre: "Animation | Adventure | Comedy",
    year: "2016",
    rating: "8.0",
    language: "Hindi",
    description: "A rabbit cop and fox con artist solve crimes.",
    views: 1900,
  },
  {
    id: 29,
    title: "Ben 10: Destroy All Aliens",
    poster: "/29id.jpg",
    trailer: "https://www.youtube.com/embed/zIYZQpknKZQ?si",
    telegramLink: "https://t.me/animeversebd/414",
    genre: "Animation | Action | Sci-Fi",
    year: "2012",
    rating: "7.3",
    language: "Dual Audio",
    description: "Ben 10 fights to save the world.",
    views: 1700,
  },
  {
    id: 30,
    title: "Shrek",
    poster: "/30id.jpg",
    trailer: "https://www.youtube.com/embed/V2WydtFqZP8?si",
    telegramLink: "https://t.me/animeversebd/416",
    genre: "Animation | Comedy | Fantasy",
    year: "2001",
    rating: "7.1",
    language: "English/Hindi",
    description: "An ogre rescues a princess.",
    views: 1650,
  },
  {
    id: 31,
    title: "Shrek 2",
    poster: "/31id.jpg",
    trailer: "https://www.youtube.com/embed/YxXp4EB6-fQ?si",
    telegramLink: "https://t.me/animeversebd/418",
    genre: "Animation | Comedy | Adventure",
    year: "2004",
    rating: "7.2",
    language: "English",
    description: "Shrek meets his in-laws.",
    views: 1700,
  },
  {
    id: 32,
    title: "The Jungle Book",
    poster: "/32id.jpg",
    trailer: "https://www.youtube.com/embed/q6ZbvucX4Pg?si",
    telegramLink: "https://t.me/animeversebd/419",
    genre: "Animation | Adventure | Family",
    year: "1967",
    rating: "6.7",
    language: "Dual Audio",
    description: "A boy grows up in the jungle.",
    views: 1550,
  },
  {
    id: 33,
    title: "The Secret Life of Pets 2",
    poster: "/33id.jpg",
    trailer: "https://www.youtube.com/embed/Id9iHnlOZaI?si",
    telegramLink: "https://t.me/animeversebd/421",
    genre: "Animation | Comedy | Family",
    year: "2019",
    rating: "6.4",
    language: "English",
    description: "Pets go on new adventures.",
    views: 1450,
  },
  {
    id: 34,
    title: "Turbo",
    poster: "/34id.jpg",
    trailer: "https://www.youtube.com/embed/VlRtm8Gh9PQ?si",
    telegramLink: "https://t.me/animeversebd/423",
    genre: "Animation | Adventure | Comedy",
    year: "2013",
    rating: "7.8",
    language: "Dual Audio",
    description: "A snail dreams of racing.",
    views: 2890,
  },
  {
    id: 35,
    title: "White Snake",
    poster: "/35id.jpg",
    trailer: "https://www.youtube.com/embed/RYKRko-yaO4?si",
    telegramLink: "https://t.me/animeversebd/425",
    genre: "Animation | Fantasy | Romance",
    year: "2019",
    rating: "7.4",
    language: "Dual Audio",
    description: "A magical love story unfolds.",
    views: 1750,
  },
  {
    id: 36,
    title: "Wonder Park",
    poster: "/36id.jpg",
    trailer: "https://www.youtube.com/embed/kNIyjsmoKts?si",
    telegramLink: "https://t.me/animeversebd/427",
    genre: "Animation | Family | Fantasy",
    year: "2019",
    rating: "7.0",
    language: "English/Hindi",
    description: "A girl brings her imagination to life.",
    views: 1678,
  },
  {
    id: 37,
    title: "Mojib Bai",
    poster: "/37id.jpg",
    trailer: "https://www.youtube.com/embed/givLtqsybMo?si",
    telegramLink: "https://t.me/animeversebd/429",
    genre: "Animation | Adventure | Action",
    year: "2015",
    rating: "6.6",
    language: "Bangla",
    description: "A Bangladeshi animated adventure.",
    views: 1500,
  },
  {
    id: 38,
    title: "Madan Senki Ryukendo",
    poster: "/38id.jpg",
    trailer: "https://www.youtube.com/embed/vNgF_ZbVZHk?si",
    telegramLink: "https://t.me/animeversebd/431",
    genre: "Action | Fantasy | Tokusatsu",
    year: "2006",
    rating: "7.3",
    language: "Japanese/English",
    description: "A warrior fights for justice.",
    views: 1700,
  },
  {
    id: 39,
    title: "What If... Season 1",
    poster: "/39id.jpg",
    trailer: "https://www.youtube.com/embed/I7ztyv9dwgo?si",
    telegramLink: "https://t.me/animeversebd/536",
    genre: "Animation | Action | Sci-Fi",
    year: "2021",
    rating: "7.1",
    language: "English/Hindi",
    description: "Explore alternate Marvel universes.",
    views: 1650,
  },
  {
    id: 40,
    title: "SK8 the Infinity Season 1",
    poster: "/40id.jpg",
    trailer: "https://www.youtube.com/embed/cBPPj83KjTQ?si",
    telegramLink: "https://t.me/animeversebd/555",
    genre: "Sports | Action | Comedy",
    year: "2021",
    rating: "7.2",
    language: "Japanese/Hindi",
    description: "Underground skateboarding battles.",
    views: 1700,
  },
  {
    id: 41,
    title: "Death Note Season 1",
    poster: "/41id.jpg",
    trailer: "https://www.youtube.com/embed/R5JgNbmQBcY?si",
    telegramLink: "https://t.me/animeversebd/578",
    genre: "Mystery | Supernatural | Thriller",
    year: "2006",
    rating: "8.9",
    language: "Japanese/Hindi",
    description: "A notebook that can kill anyone.",
    views: 2400,
  },
  {
    id: 42,
    title: "Roll No. 21 Season 1",
    poster: "/42id.jpg",
    trailer: "https://www.youtube.com/embed/Zx4Yu2cujqI?si",
    telegramLink: "https://t.me/animeversebd/585",
    genre: "Animation | Comedy | Adventure",
    year: "2010",
    rating: "8.1",
    language: "Hindi",
    description: "A student's hilarious adventures.",
    views: 2000,
  },
  {
    id: 43,
    title: "Roll No. 21 Season 2",
    poster: "/43id.jpg",
    trailer: "https://www.youtube.com/embed/LTeXi8LgTy4?si",
    telegramLink: "https://t.me/animeversebd/632",
    genre: "Animation | Comedy | Adventure",
    year: "2013",
    rating: "7.8",
    language: "Dual Audio",
    description: "More adventures of Roll No. 21.",
    views: 1900,
  },
  {
    id: 44,
    title: "Baki Hanma Season 2",
    poster: "/44id.jpg",
    trailer: "https://www.youtube.com/embed/KN98VzNwjOY?si",
    telegramLink: "https://t.me/animeversebd/685",
    genre: "Action | Martial Arts | Anime",
    year: "2023",
    rating: "7.4",
    language: "Japanese/Hindi",
    description: "Intense martial arts battles.",
    views: 1750,
  },
  {
    id: 45,
    title: "Blue Eye Samurai Season 1",
    poster: "/45id.jpg",
    trailer: "https://www.youtube.com/embed/WfzXxTq_W6k?si",
    telegramLink: "https://t.me/animeversebd/738",
    genre: "Animation | Action | Drama",
    year: "2023",
    rating: "7.0",
    language: "Hindi/Japanese",
    description: "A samurai's quest for revenge.",
    views: 4567,
  },
]

export const animeGenres = [
  "Action",
  "Comedy",
  "Drama",
  "Adventure",
  "Supernatural",
  "Fantasy",
  "Sci-Fi",
  "Thriller",
  "Romance",
  "Historical",
  "School",
  "Martial Arts",
]
