export const movies4 = [

{
    id: 3105,
    title: "The Madness (2024) – Season 1",
    poster: "/3105id.jpg",
    trailer: "https://www.youtube.com/embed/gLY42ueSSD8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4MTAsMTQ4Mjg",
    genre: "Thriller | Mystery | Crime | Drama",
    year: "2024",
    rating: "6.5",
    language: "Hindi",
    description: "এক মিডিয়া বিশ্লেষক একটি ভয়ংকর হত্যাকাণ্ডের পর ষড়যন্ত্রের জালে জড়িয়ে পড়ে। নিজের নির্দোষিতা প্রমাণ করতে গিয়ে তাকে পালাতে পালাতে এক ভয়ংকর সত্যের সন্ধান করতে হয়।",
    views: 23847,
  },
  {
    id: 3106,
    title: "Countdown Season 1 (2025)",
    poster: "/3106id.jpg",
    trailer: "https://www.youtube.com/embed/FCBDuQhkx2A?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4MjksMTQ4NTc",
    genre: "Action | Thriller | Drama",
    year: "2025",
    rating: "6.8",
    language: "Hindi",
    description: "এক ভয়ংকর হুমকির বিরুদ্ধে সময়ের সঙ্গে পাল্লা দিয়ে একদল মানুষকে গুরুত্বপূর্ণ রহস্য উন্মোচন করতে হয়। সময় শেষ হওয়ার আগেই তাদের জীবন বাঁচানোর লড়াই শুরু হয়।",
    views: 23847,
  },
  {
    id: 3107,
    title: "The Nightwatchman – Season 1 (2019)",
    poster: "/3107id.jpg",
    trailer: "https://www.youtube.com/embed/CRk2EnxaREA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NTgsMTQ4NzI",
    genre: "Crime | Thriller | Drama | bangla",
    year: "2019",
    rating: "4.6",
    language: "Bangla",
    description: "এক তরুণ আকর্ষণীয় বেতনের চাকরির প্রস্তাব পেয়ে রাতের পাহারাদারের কাজ শুরু করে। কিন্তু চাকরিটির পেছনে লুকিয়ে থাকা অন্ধকার রহস্য ধীরে ধীরে তার জীবনকে বিপদের দিকে ঠেলে দেয়।" ,
    views: 23847,
  },
  {
    id: 3108,
    title: "The Thieves (2012)",
    poster: "/3108id.jpg",
    trailer: "https://www.youtube.com/embed/28qTsiPhYCI?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzMsMTQ4NzQ",
    genre: "Action | Crime | Thriller | Comedy",
    year: "2012",
    rating: "6.8",
    language: "Hindi",
    description: "দক্ষিণ কোরিয়া ও চীনের একদল দক্ষ চোর একটি মূল্যবান হীরার হার চুরি করতে একত্রিত হয়। কিন্তু প্রত্যেকের নিজস্ব পরিকল্পনা থাকায় বিশাল চুরির মিশনটি ধীরে ধীরে বিশ্বাসঘাতকতা ও বিপদের খেলায় পরিণত হয়।",
    views: 23847,
  },
  {
    id: 3109,
    title: "Surrender (2025)",
    poster: "/3109id.jpg",
    trailer: "https://www.youtube.com/embed/GNPkKsV5f34?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzUsMTQ4NzY",
    genre: "Thriller | Drama",
    year: "2025",
    rating: "6.5",
    language: "Hindi",
    description: "এক ভয়ংকর পরিস্থিতিতে আটকে পড়া এক ব্যক্তি বাঁচার জন্য কঠিন সিদ্ধান্ত নিতে বাধ্য হয়। সময়ের সঙ্গে পরিস্থিতি আরও জটিল হয়ে উঠলে সত্য ও বিশ্বাসের পরীক্ষা শুরু হয়।",
    views: 23847,
  },
  {
    id: 3110,
    title: "Cassette 2 (2026)",
    poster: "/3110id.jpg",
    trailer: "https://www.youtube.com/embed/JU-E08zTOlk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzcsMTQ4Nzg",
    genre: "Drama | Thriller | Mystery",
    year: "2026",
    rating: "7.3",
    language: "Hindi",
    description: "একটি রহস্যময় ক্যাসেট ঘিরে পুরোনো কিছু ঘটনা ও গোপন সত্য ধীরে ধীরে সামনে আসে। সত্য উদঘাটনের চেষ্টা করতে গিয়ে চরিত্রগুলো আরও গভীর রহস্য ও বিপদের মধ্যে জড়িয়ে পড়ে।",
    views: 23847,
  },
  {
    id: 3111,
    title: "Hawa Bodol (2013)",
    poster: "/3111id.jpg",
    trailer: "https://www.youtube.com/embed/G22ivKXtRvg?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzksMTQ4ODA",
    genre: "Comedy | Drama | Fantasy | bangla",
    year: "2013",
    rating: "7.1",
    language: "Bangla",
    description: "দুই ভিন্ন স্বভাবের মানুষের জীবন হঠাৎ বদলে গেলে তারা একে অপরের জীবনযাপন করতে বাধ্য হয়। এই অদ্ভুত পরিস্থিতি থেকেই তৈরি হয় হাস্যরস, আবেগ ও জীবনের নতুন উপলব্ধির গল্প।",
    views: 23847,
  },
  {
    id: 3112,
    title: "Bonyo Premer Golpo (2020)",
    poster: "/3112id.jpg",
    trailer: "https://www.youtube.com/embed/UVvaSXbTO04?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4ODEsMTQ4OTc",
    genre: "Romance | Drama | bangla",
    year: "2020",
    rating: "6.5",
    language: "Bangla",
    description: "অপরাধজগতের ক্ষমতা ও আধিপত্যের লড়াইকে কেন্দ্র করে এক গ্যাংস্টারের উত্থান ও সংঘর্ষের গল্প। প্রতিশোধ, বিশ্বাসঘাতকতা ও অ্যাকশনে ভরা এই কাহিনিতে ক্ষমতার জন্য শুরু হয় ভয়ংকর লড়াই। 🔥🔫⚔️",
    views: 23847,
  },
  {
    id: 3113,
    title: "Frankenstein's Bride (2026)",
    poster: "/3113id.jpg",
    trailer: "https://www.youtube.com/embed/mSC4pRodc2Y?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4OTgsMTQ4OTk",
    genre: "Horror | Sci-Fi | Drama",
    year: "2026",
    rating: "7.1",
    language: "Hindi",
    description: "ভিক্টর ফ্রাঙ্কেনস্টাইন তার সৃষ্ট প্রাণীর জন্য এক সঙ্গী তৈরি করতে চায়। কিন্তু নতুন সৃষ্টির আগমন থেকেই শুরু হয় ভালোবাসা, অস্তিত্ব ও নিয়ন্ত্রণকে ঘিরে ভয়ংকর এক সংঘাত।",
    views: 23847,
  },
  {
    id: 3114,
    title: "Resident Playbook (2025) – Season 1",
    poster: "/3114id.jpg",
    trailer: "https://www.youtube.com/embed/sWtOe9DIK9o?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5MDAsMTQ5MjY",
    genre: "kdrama | Medical | Drama | Comedy",
    year: "2025",
    rating: "8.0",
    language: "English",
    description: "ইউলজে মেডিকেল সেন্টারের নতুন OB-GYN রেসিডেন্টরা কঠিন চিকিৎসা-জীবন, রোগী সামলানো ও ব্যক্তিগত সমস্যার সঙ্গে লড়াই করতে করতে দক্ষ ডাক্তার হয়ে ওঠার চেষ্টা করে।",
    views: 23847,
  },
  {
    id: 3115,
    title: "Saas Bahu Achaar Pvt. Ltd. (2022) – Season 1",
    poster: "/3115id.jpg",
    trailer: "https://www.youtube.com/embed/QjcYGkEMuj4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5MjcsMTQ5NDE",
    genre: "Drama | Family",
    year: "2022",
    rating: "8.2",
    language: "Hindi",
    description: "স্বামীকে ছেড়ে সন্তানদের ফিরে পাওয়ার আশায় সুমন নিজের আচার ব্যবসা শুরু করে। নানা বাধা পেরিয়ে নিজের পায়ে দাঁড়িয়ে নতুন জীবন গড়ার লড়াই শুরু হয় তার।",
    views: 23847,
  },
  {
    id: 3116,
    title: "Monster Island (2024)",
    poster: "/3116id.jpg",
    trailer: "https://www.youtube.com/embed/O-XgvNtiNIE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDIsMTQ5NDM",
    genre: "Horror | Fantasy | Action | Thriller",
    year: "2024",
    rating: "5.2",
    language: "Hindi",
    description: "দ্বিতীয় বিশ্বযুদ্ধের সময় এক জাপানি সৈনিক ও এক ব্রিটিশ যুদ্ধবন্দী নির্জন দ্বীপে আটকা পড়ে। শত্রুতা ভুলে তাদের একসঙ্গে লড়তে হয় ভয়ংকর এক দানবের হাত থেকে বাঁচার জন্য।",
    views: 23847,
  },
  {
    id: 3117,
    title: "Tarikh (2019)",
    poster: "/3117id.jpg",
    trailer: "https://www.youtube.com/embed/4Z6iCxKUaSM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDQsMTQ5NDU",
    genre: "Action | Thriller | bangla",
    year: "2019",
    rating: "6.6",
    language: "Bangla",
    description: "তিন বন্ধুর জীবনে মৃত্যু, সম্পর্ক ও বিশ্বাসের টানাপোড়েন তাদের জীবনকে নতুনভাবে ভাবতে বাধ্য করে। জীবনের প্রতিটি মুহূর্তের মূল্য আর মানুষের অস্তিত্বের অর্থ নিয়েই এগিয়ে যায় গল্পটি।",
    views: 23847,
  },
  {
    id: 3118,
    title: "P Se Pyaar F Se Faraar (2019)",
    poster: "/3118id.jpg",
    trailer: "https://www.youtube.com/embed/ipMd5SSuxbE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDYsMTQ5NDc",
    genre: "Crime | Drama | Romance",
    year: "2019",
    rating: "5.2",
    language: "Hindi",
    description: "ভিন্ন সামাজিক অবস্থানের দুই তরুণ-তরুণী প্রেম করে পালিয়ে বিয়ে করলে তাদের জীবন ভয়ংকর সামাজিক প্রতিশোধ ও সম্মান হত্যার হুমকির মুখে পড়ে।",
    views: 23847,
  },
  {
    id: 3119,
    title: "Raakaasa (2026)",
    poster: "/3119id.jpg",
    trailer: "https://www.youtube.com/embed/TJ5dpuZ1cAk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDgsMTQ5NDk",
    genre: "Comedy | Fantasy | Horror | Mystery | bangla",
    year: "2026",
    rating: "6.7",
    language: "Bangla",
    description: "দশ বছর পর আমেরিকা থেকে নিজের গ্রামে ফিরে প্রেমের খোঁজে নামে বীরবাবু। কিন্তু ভুলবশত সে জাগিয়ে তোলে বহুদিনের লুকিয়ে থাকা এক ভয়ংকর প্রাচীন অশুভ শক্তি, যার পরিণতিতে প্রেম পরিণত হয় জীবন-মরণ লড়াইয়ে।",
    views: 23847,
  },
  {
    id: 3120,
    title: "Byomkesh O Agnibaan (2017)",
    poster: "/3120id.jpg",
    trailer: "https://www.youtube.com/embed/Tc9y-8Q4Qik?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTAsMTQ5NTE",
    genre: "Mystery | Thriller | bangla",
    year: "2017",
    rating: "7.1",
    language: "Bangla",
    description: "এক তরুণীর রহস্যময় মৃত্যুর তদন্তে নেমে ব্যোমকেশ এমন এক জটিল রহস্যের মুখোমুখি হয়, যার সঙ্গে প্রতিশোধ ও পুরনো অপরাধের যোগসূত্র রয়েছে।",
    views: 23847,
  },
  {
    id: 3121,
    title: "The Invisible Man (2020)",
    poster: "/3121id.jpg",
    trailer: "https://www.youtube.com/embed/9udDdR4TrmE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTIsMTQ5NTM",
    genre: "Horror | Sci-Fi | Thriller | Mystery",
    year: "2020",
    rating: "7.1",
    language: "Hindi",
    description: "এক নারী তার ভয়ংকর প্রাক্তন প্রেমিকের হাত থেকে পালানোর পর বিশ্বাস করতে শুরু করে যে সে অদৃশ্য হয়ে তাকে অনুসরণ করছে। কিন্তু কেউ তার কথা বিশ্বাস না করায় শুরু হয় বাঁচার এক ভয়ংকর লড়াই।",
    views: 23847,
  },
  {
    id: 3122,
    title: "The Messenger: The Story of Joan of Arc (1999)",
    poster: "/3122id.jpg",
    trailer: "https://www.youtube.com/embed/aCbMOQIs45s?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTQsMTQ5NTU",
    genre: "Biography | Drama | War | History",
    year: "1999",
    rating: "6.4",
    language: "Hindi",
    description: "যুদ্ধবিধ্বস্ত ফ্রান্সে তরুণী জোয়ান অব আর্ক ঈশ্বরের নির্দেশ পাওয়ার দাবি করে ফরাসি সেনাবাহিনীকে নেতৃত্ব দেয়। তার সাহস, বিশ্বাস ও আত্মত্যাগ তাকে ইতিহাসের এক কিংবদন্তি চরিত্রে পরিণত করে।",
    views: 23847,
  },
  {
    id: 3123,
    title: "Widows (2018)",
    poster: "/3123id.jpg",
    trailer: "https://www.youtube.com/embed/nN2yBBSRC78?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTYsMTQ5NTc",
    genre: "Crime | Drama | Thriller",
    year: "2018",
    rating: "6.8",
    language: "Hindi",
    description: "চার বিধবা নারী তাদের মৃত স্বামীদের রেখে যাওয়া ঋণ শোধ করতে এক অসম্ভব ডাকাতির পরিকল্পনা করে। কিন্তু পরিকল্পনা যত এগোয়, তারা ততই জড়িয়ে পড়ে রাজনীতি, অপরাধ আর বিশ্বাসঘাতকতার জালে।",
    views: 23847,
  },
  {
    id: 3124,
    title: "Mirzapur (2026)",
    poster: "/3124id.jpg",
    trailer: "https://www.youtube.com/embed/5vMWZhHPlaw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTgsMTQ5NTk",
    genre: "Action | Crime | Thriller | Drama",
    year: "2026",
    rating: "6.7",
    language: "Hindi",
    description: "মির্জাপুরের ক্ষমতা, রাজনীতি ও অপরাধজগতকে ঘিরে এক নতুন গল্প। পুরোনো শত্রুতা, প্রতিশোধ ও ক্ষমতার লড়াইয়ের মাঝে নতুন চরিত্রদের উত্থানে পরিস্থিতি আরও উত্তপ্ত হয়ে ওঠে। 🔥👑⚔️🖤",
    views: 23847,
  },
  {
    id: 3125,
    title: "I'm Game (2026)",
    poster: "/3125id.jpg",
    trailer: "https://www.youtube.com/embed/G2aaDEXNq20?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjAsMTQ5NjE",
    genre: "Thriller | Mystery | Drama",
    year: "2026",
    rating: "7.8",
    language: "Hindi",
    description: "এক রহস্যময় গেমে জড়িয়ে পড়ার পর এক তরুণ বুঝতে পারে, এটি শুধুই বিনোদন নয়। গেমের প্রতিটি ধাপ তাকে নতুন রহস্য ও অপ্রত্যাশিত চ্যালেঞ্জের মুখোমুখি করে। 🎮🔍⚡️",
    views: 23847,
  },
  {
    id: 3126,
    title: "Wolf Pack (2022)",
    poster: "/3126id.jpg",
    trailer: "https://www.youtube.com/embed/mPnTzS-Gkzg?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjIsMTQ5NjM",
    genre: "Action | Thriller | War",
    year: "2022",
    rating: "4.9",
    language: "Hindi",
    description: "বিদেশে নিরাপত্তা মিশনে থাকা Wolf Pack স্কোয়াড আবিষ্কার করে যে সন্ত্রাসী একটি দল চীনের গুরুত্বপূর্ণ জ্বালানি ব্যবস্থায় হামলার পরিকল্পনা করছে। এরপর দেশকে রক্ষা করতে শুরু হয় ভয়ংকর এক মিশন।",
    views: 23847,
  },
  {
    id: 3127,
    title: "jekhane bhuter bhoy (2012)",
    poster: "/3127id.jpg",
    trailer: "https://www.youtube.com/embed/3E8HGhSNEvA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjQsMTQ5NjU",
    genre: "bangla | Horror | Comedy | Mystery",
    year: "2012",
    rating: "7.2",
    language: "Bangla",
    description: "চারটি ভৌতিক গল্পের মাধ্যমে কলকাতার বিভিন্ন জায়গায় ঘটে যাওয়া অদ্ভুত ও রহস্যময় ঘটনার কাহিনি তুলে ধরা হয়েছে। ভয় আর হাসির মিশেলে এগিয়ে যায় চার ভূতের মজার গল্প।",
    views: 23847,
  }, 
  {
    id: 3128,
    title: "Coke / Human Cocaine (2026)",
    poster: "/3128id.jpg",
    trailer: "https://www.youtube.com/embed/XdHH2vDb0SM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjYsMTQ5Njc",
    genre: "Action | Crime | Thriller",
    year: "2026",
    rating: "5.7",
    language: "Hindi",
    description: "পরিবারকে ফিরে পাওয়ার আশায় ক্যাবচালক অর্জুন একটি লাভজনক ডেলিভারির কাজ নেয়। কিন্তু পথে এক অচেনা যাত্রীকে সাহায্য করতে গিয়ে সে ইউরোপের ভয়ংকর মাদকচক্রের হাতে বন্দি হয়ে যায়।",
    views: 23847,
  },
  {
    id: 3129,
    title: "Kangaroo Kids (2026)",
    poster: "/3129id.jpg",
    trailer: "https://www.youtube.com/embed/WeOHwTVjvVQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjgsMTQ5Njk",
    genre: "Comedy | Drama | Family",
    year: "2026",
    rating: "7.8",
    language: "Hindi",
    description: "কয়েকজন কিশোর-কিশোরীর বন্ধুত্ব, স্কুলজীবন ও নানা মজার ঘটনার মধ্য দিয়ে এগিয়ে চলে গল্প। তাদের দুষ্টুমি, স্বপ্ন ও পারিবারিক সম্পর্ক মিলিয়ে তৈরি হয় আনন্দঘন এক কাহিনি। 🎒😂❤️✨",
    views: 23847,
  },
  {
    id: 3130,
    title: "Star Wars: The Mandalorian and Grogu (2026)",
    poster: "/3130id.jpg",
    trailer: "https://www.youtube.com/embed/ROn_r35ioV8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzAsMTQ5NzE",
    genre:  "ion | Adventure | Fantasy | Sci-Fi",
    year: "2026",
    rating: "6.8",
    language: "Hindi",
    description: "গ্যালাক্সিতে নতুন বিপদের মুখে ম্যান্ডালোরিয়ান দিন জারিন ও তার শিষ্য গ্রোগু এক দুর্ধর্ষ মিশনে বের হয়। পথে সাম্রাজ্যের অবশিষ্ট শক্তির বিরুদ্ধে লড়াই করতে গিয়ে তাদের বন্ধন ও সাহসের কঠিন পরীক্ষা হয়।",
    views: 23847,
  },
  {
    id: 3131,
    title: "The Runner (2026)",
    poster: "/3131id.jpg",
    trailer: "https://www.youtube.com/embed/nPjcXUYboDE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzIsMTQ5NzM",
    genre: "Action | Thriller | Drama | Mystery",
    year: "2026",
    rating: "5.9",
    language: "Hindi",
    description: "লন্ডনের আইনজীবী মাইয়ার ছেলেকে অপহরণ করে এক রহস্যময় ব্যক্তি। ছেলেকে বাঁচাতে তাকে শহরজুড়ে দৌড়াতে ও একের পর এক ভয়ংকর নির্দেশ পালন করতে হয়।",
    views: 23847,
  },
  {
    id: 3132,
    title: "The Wrath of God (2022)",
    poster: "/3132id.jpg",
    trailer: "https://www.youtube.com/embed/b6YpZl1gl8s?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzQsMTQ5NzU",
    genre: "Mystery | Thriller | Drama | netflix",
    year: "2022",
    rating: "6.0",
    language: "Hindi",
    description: "এক লেখক তার জীবনে ঘটে যাওয়া একের পর এক রহস্যময় মৃত্যুর পেছনে তার সাবেক বসের হাত রয়েছে বলে সন্দেহ করে। সত্য উদঘাটন করতে গিয়ে সে প্রতিশোধ, ভয় আর অন্ধকার রহস্যের মুখোমুখি হয়।",
    views: 23847,
  },
  {
    id: 3133,
    title: "ISHQ (Don't Fall in Love) (2024)",
    poster: "/3133id.jpg",
    trailer: "https://www.youtube.com/embed/ZO8TkW-vZDs?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzYsMTQ5Nzc",
    genre: "Sci-Fi | Drama | Mystery",
    year: "2024",
    rating: "6.6",
    language: "Hindi",
    description: "বিয়ে ও সম্পর্কের প্রতি আস্থা হারিয়ে রাম সিঙ্গেল থাকার সিদ্ধান্ত নেয়। কিন্তু পরিবারের বিয়ের চাপের মাঝে এক মেয়ের সঙ্গে তার দেখা হলে ভালোবাসা ও জীবনের সিদ্ধান্ত নিয়ে নতুন দ্বন্দ্ব শুরু হয়।",
    views: 23847,
  },
  {
    id: 3134,
    title: "The Legend of ShenLi (2024) – Season 1",
    poster: "/3134id.jpg",
    trailer: "https://www.youtube.com/embed/hC00-C6p5og?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzgsMTUwMDA",
    genre: "kdrama | Fantasy | Romance | Action | Historical",
    year: "2024",
    rating: "8.1",
    language: "Hindi",
    description: "ডেমন জগতের শক্তিশালী যোদ্ধা শেন লি পালিয়ে মানবজগতে এসে গুরুতর আহত অবস্থায় এক রহস্যময় পুরুষের সাহায্য পায়। ধীরে ধীরে তাদের মধ্যে প্রেমের জন্ম হলেও অতীতের পরিচয় ও স্বর্গ-দৈত্য জগতের সংঘাত তাদের সম্পর্ককে কঠিন পরীক্ষার মুখে ফেলে।",
    views: 23847,
  },
  {
    id: 3135,
    title: "Gandhari (2026)",
    poster: "/3135id.jpg",
    trailer: "https://www.youtube.com/embed/Cq58YGCO_2c?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDEsMTUwMDI",
    genre: "Action | Crime | Thriller | Mystery | Drama",
    year: "2026",
    rating: "4.8",
    language: "Hindi",
    description: "মেয়েকে অপহরণ করার পর দৃষ্টিশক্তি হারানো মা বাণী নিজেই অপরাধীদের খুঁজে বের করার লড়াইয়ে নামে। মেয়েকে উদ্ধার করতে গিয়ে সে জড়িয়ে পড়ে এক ভয়ংকর অপরাধচক্র ও প্রতিশোধের খেলায়।",
    views: 23847,
  },
  {
    id: 3136,
    title: "Unmadham (2026)",
    poster: "/3136id.jpg",
    trailer: "https://www.youtube.com/embed/zGqJqfr76ao?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDMsMTUwMDQ",
    genre: "Crime | Mystery | Psychological Thriller",
    year: "2026",
    rating: "6.3",
    language: "Hindi",
    description: "অতীতের ভারে জর্জরিত পুলিশ কনস্টেবল শেলি বহুদিনের পুরোনো একটি অমীমাংসিত মামলা আবার খুলে তদন্ত শুরু করে। তদন্ত যত এগোয়, কুসংস্কার, গোপন রহস্য ও অতিপ্রাকৃত ঘটনার মাঝে বাস্তবতা নিয়ে তার বিশ্বাসও প্রশ্নের মুখে পড়ে।",
    views: 23847,
  },
  {
    id: 3137,
    title: "Journey to the West: The Demons Strike Back (2017)",
    poster: "/3137id.jpg",
    trailer: "https://www.youtube.com/embed/PuDEs9_Jsz0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDUsMTUwMDY",
    genre: "Fantasy | Adventure | Comedy | Action",
    year: "2017",
    rating: "5.4",
    language: "Hindi",
    description: "সান উকং, ঝু বাজিয়ে ও শা উজিংকে নিয়ে তাং সানজাং আবারও বিপজ্জনক এক অভিযানে বের হয়। পথে তারা নানা দানব ও অতিপ্রাকৃত শক্তির মুখোমুখি হয়, আর বুদ্ধি ও শক্তির সাহায্যে তাদের মোকাবিলা করতে থাকে। 🐒⚔️👹",
    views: 23847,
  },
  {
    id: 3138,
    title: "Lovesick – Season 1 (2026)",
    poster: "/3138id.jpg",
    trailer: "https://www.youtube.com/embed/6vorXO9Mc-U?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDcsMTUwMjM",
    genre: "Romance | History | Drama",
    year: "2026",
    rating: "5.7",
    language: "Hindi",
    description: "মেক্সিকান বিপ্লবের অস্থির সময়ে এমিলিয়া সৌরি সমাজের প্রচলিত বাধা অতিক্রম করে ডাক্তার হওয়ার স্বপ্ন পূরণের চেষ্টা করে। একইসঙ্গে প্রেম, পরিবার, রাজনৈতিক পরিবর্তন ও নিজের স্বাধীনতার জন্য তাকে নানা কঠিন সিদ্ধান্তের মুখোমুখি হতে হয়। ❤️🩺🇲🇽",
    views: 23847,
  },
  {
    id: 3139,
    title: "Khuda Haafiz (2020)",
    poster: "/3139id.jpg",
    trailer: "https://www.youtube.com/embed/q67l_GOUzGc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMjQsMTUwMjU",
    genre: "Action | Thriller | Drama",
    year: "2020",
    rating: "7.1",
    language: "Hindi",
    description: "সমীর ও নার্গিসের নতুন জীবনের শুরুতেই নার্গিস নিখোঁজ হয়ে যায়। তাকে খুঁজে বের করতে সমীর এক বিপজ্জনক বিদেশি শহরে পাড়ি জমায় এবং অপরাধচক্রের বিরুদ্ধে লড়াইয়ে জড়িয়ে পড়ে। 🔥🔎❤️",
    views: 23847,
  },
  {
    id: 3140,
    title: "Khuda Haafiz Chapter 2: Agni Pariksha (2022)",
    poster: "/3140id.jpg",
    trailer: "https://www.youtube.com/embed/iPaSef3NtMA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMjYsMTUwMjc",
    genre: "Action | Thriller | Drama",
    year: "2022",
    rating: "7.0",
    language: "Hindi",
    description: "প্রথম সিনেমার ঘটনার পর সমীর ও নার্গিস তাদের জীবনে নতুনভাবে ঘুরে দাঁড়ানোর চেষ্টা করে। কিন্তু এক মর্মান্তিক ঘটনার পর তাদের জীবন আবারও অন্ধকারে ঢেকে যায়, আর সমীর ন্যায়বিচারের জন্য কঠিন লড়াইয়ে নামতে বাধ্য হয়। ⚔️🔥💔",
    views: 23847,
  }, 
    {
    id: 3141,
    title: "Filing for Love (2026) – Season 1",
    poster: "/3141id.jpg",
    trailer: "https://www.youtube.com/embed/q67l_GOUzGc?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUwMjgsMTUwNTQ",
    genre: "Romance | Comedy | Drama | kdrama",
    year: "2026",
    rating: "7.4",
    language: "Hindi",
    description: "অডিট টিমের সেরা কর্মী নো কি-জুন হঠাৎ পদাবনতি পেয়ে কঠোর অডিট পরিচালক জু ইন-আহর অধীনে কাজ শুরু করে। অফিসের ঝামেলা ও তদন্তের মাঝেই তাদের দ্বন্দ্ব ধীরে ধীরে অপ্রত্যাশিত ভালোবাসায় রূপ নেয়।",
    views: 23847,
  },
  {
    id: 3142,
    title: "Aashram (2022) – Season 3",
    poster: "/3142id.jpg",
    trailer: "https://www.youtube.com/embed/iPaSef3NtMA?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUwNTUsMTUwNzc",
    genre: "Crime | Drama | Thriller",
    year: "2022",
    rating: "7.0",
    language: "Hindi",
    description: "বাবা নিরালার ক্ষমতা ও প্রভাব আরও বাড়তে থাকে, কিন্তু তার আশ্রমের অন্ধকার সত্য ধীরে ধীরে প্রকাশ পেতে শুরু করে। প্রতিশোধ, রাজনীতি ও অপরাধের মাঝে এবার শুরু হয় তার সাম্রাজ্য টিকিয়ে রাখার লড়াই।",
    views: 23847,
  },
    {
    id: 3143,
    title: "The Silent Promise (2025)",
    poster: "/3143id.jpg",
    trailer: "https://www.youtube.com/embed/YsVo5necW6Q?si",
    telegramLink: "https://t.me/MoviesVerseBD/1197",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2025",
    rating: "3.8",
    language: "Japanese",
    description: "একটি পুরোনো প্রতিশ্রুতির রহস্য বহু বছর পর আবার সামনে আসে। সত্যের খোঁজে এগিয়ে গিয়ে একজন মানুষ আবিষ্কার করে তার অতীতের সঙ্গে জড়িয়ে থাকা এক অজানা গল্প। 🤫🔍🌙",
    views: 23847,
  },
  {
    id: 3144,
    title: "Beyond the Last Goodbye (2025)",
    poster: "/3144id.jpg",
    trailer: "https://www.youtube.com/embed/hf3gO0lpPOg?si",
    telegramLink: "https://t.me/MoviesVerseBD/1199",
    genre: "Adult | Drama | Mystery | Romance",
    year: "2025",
    rating: "7.4",
    language: "Japanese",
    description: "একটি বিচ্ছেদের পরও কিছু স্মৃতি থেকে যায়। সেই স্মৃতির সূত্র ধরে শুরু হয় এমন এক যাত্রা, যেখানে পুরোনো সত্য আর নতুন অনুভূতি মুখোমুখি হয়। 🌧️💭✨",
    views: 23847,
  },
  {
    id: 3145,
    title: "Echoes of Yesterday (2025)",
    poster: "/3145id.jpg",
    trailer: "https://www.youtube.com/embed/QXG7sJ3saB0?si",
    telegramLink: "https://t.me/MoviesVerseBD/1201",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2025",
    rating: "5.8",
    language: "Japanese",
    description: "একটি রহস্যময় বার্তা অতীতের ভুলে যাওয়া ঘটনাগুলোকে আবার জীবন্ত করে তোলে। সত্য উদঘাটনের পথে প্রতিটি উত্তর যেন আরও নতুন প্রশ্নের জন্ম দেয়। 📩🔍🌑",
    views: 23847,
  }, 
  {
    id: 3146,
    title: "The Hidden Door (2025)",
    poster: "/3146id.jpg",
    trailer: "https://www.youtube.com/embed/gLY42ueSSD8?si",
    telegramLink: "https://t.me/MoviesVerseBD/1203",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2025",
    rating: "6.6",
    language: "Japanese",
    description: "একটি পুরোনো বাড়িতে পাওয়া অজানা দরজা খুলে দেয় রহস্যের নতুন অধ্যায়। এর ওপাশে লুকিয়ে থাকা সত্য পুরো পরিবারের জীবন বদলে দিতে শুরু করে। 🚪🏚️🔍",
    views: 23847,
  },
  {
    id: 3147,
    title: "Falling Into the Unknown (2025)",
    poster: "/3147id.jpg",
    trailer: "https://www.youtube.com/embed/FCBDuQhkx2A?si",
    telegramLink: "https://t.me/MoviesVerseBD/1206",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2025",
    rating: "5.4",
    language: "Japanese",
    description: "অচেনা এক পরিস্থিতিতে আটকে পড়ে একজন তরুণ। বেরিয়ে আসার চেষ্টা করতে গিয়ে সে এমন এক গোপন জগতের সন্ধান পায়, যার অস্তিত্ব সে কখনো কল্পনাও করেনি। 🌌🔦🕵️",
    views: 23847,
  },
  {
    id: 3148,
    title: "The Forgotten Chapter (2025)",
    poster: "/3148id.jpg",
    trailer: "https://www.youtube.com/embed/CRk2EnxaREA?si",
    telegramLink: "https://t.me/MoviesVerseBD/1208",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2025",
    rating: "7.3",
    language: "Japanese",
    description: "একটি পরিবারের ইতিহাসের হারিয়ে যাওয়া অধ্যায় হঠাৎ করেই সামনে আসে। পুরোনো নথি আর স্মৃতির সূত্র ধরে শুরু হয় সত্য উদঘাটনের চেষ্টা। 📖🔍🌙" ,
    views: 23847,
  },
  {
    id: 3149,
    title: "A Secret in the Rain (2025)",
    poster: "/3149id.jpg",
    trailer: "https://www.youtube.com/embed/28qTsiPhYCI?si",
    telegramLink: "https://t.me/MoviesVerseBD/1210",
    genre: "Adult | Drama | Mystery | Romance",
    year: "2025",
    rating: "5.6",
    language: "Japanese",
    description: "বৃষ্টিভেজা এক সন্ধ্যায় ঘটে যাওয়া একটি ঘটনা দুই মানুষের জীবনকে অপ্রত্যাশিতভাবে বদলে দেয়। সময়ের সঙ্গে সেই রাতের আসল রহস্য ধীরে ধীরে প্রকাশ পায়। 🌧️🌃🔍",
    views: 23847,
  },
  {
    id: 3150,
    title: "Shadows of the Past (2025)",
    poster: "/3150id.jpg",
    trailer: "https://www.youtube.com/embed/GNPkKsV5f34?si",
    telegramLink: "https://t.me/MoviesVerseBD/1212",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2025",
    rating: "6.4",
    language: "Japanese",
    description: "অতীতকে পেছনে ফেলে নতুন জীবন শুরু করলেও পুরোনো রহস্য আবার ফিরে আসে। এবার সত্যের মুখোমুখি হওয়া ছাড়া আর কোনো পথ থাকে না। 🌑🕰️🔍",
    views: 23847,
  },
  {
    id: 3151,
    title: "The Final Truth (2025)",
    poster: "/3151id.jpg",
    trailer: "https://www.youtube.com/embed/JU-E08zTOlk?si",
    telegramLink: "https://t.me/MoviesVerseBD/1214",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2025",
    rating: "6.3",
    language: "Japanese",
    description: "একটি অসম্পূর্ণ রহস্যের শেষ সূত্র খুঁজে পেয়ে একজন মানুষ সত্যের একেবারে কাছাকাছি পৌঁছে যায়। কিন্তু শেষ সত্যটি প্রকাশ পাওয়ার পর সবকিছু কি আগের মতো থাকবে? 🔐🔍🌙✨",
    views: 23847,
  },
  {
    id: 3152,
    title: "The Missing Memory (2025)",
    poster: "/3152id.jpg",
    trailer: "https://www.youtube.com/embed/G22ivKXtRvg?si",
    telegramLink: "https://t.me/MoviesVerseBD/1216",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2025",
    rating: "5.9",
    language: "Japanese",
    description: "একটি হারিয়ে যাওয়া স্মৃতির সূত্র ধরে শুরু হয় রহস্যময় অনুসন্ধান। অতীতের টুকরো টুকরো ঘটনা একত্র হতে থাকলে সামনে আসে এক অপ্রত্যাশিত সত্য। 🧩🧠🔍🌙",
    views: 23847,
  },
  {
    id: 3153,
    title: "Secrets After Midnight (2025)",
    poster: "/3153id.jpg",
    trailer: "https://www.youtube.com/embed/UVvaSXbTO04?si",
    telegramLink: "https://t.me/MoviesVerseBD/1218",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2025",
    rating: "4.9",
    language: "Japanese",
    description: "মধ্যরাতের পর ঘটে যাওয়া একটি অদ্ভুত ঘটনা পুরো পরিস্থিতিকে বদলে দেয়। সেই রাতের রহস্য উন্মোচন করতে গিয়ে প্রকাশ পেতে থাকে বহুদিনের গোপন সত্য। 🌙🕛🔍✨",
    views: 23847,
  },
  {
    id: 3154,
    title: "The Forgotten school (2025)",
    poster: "/3154id.jpg",
    trailer: "https://www.youtube.com/embed/mSC4pRodc2Y?si",
    telegramLink: "https://t.me/MoviesVerseBD/1220",
    genre: "Adult | Mystery | Horror | Thriller",
    year: "2025",
    rating: "6.4",
    language: "Japanese",
    description: "শহরের প্রান্তে থাকা পরিত্যক্ত একটি বাড়ি ঘিরে ছড়িয়ে আছে অজানা রহস্য। সেখানে ফিরে আসার পর এক পরিবার অতীতের এমন কিছু সত্য আবিষ্কার করে, যা তারা কখনো জানতে চায়নি। 🏚️🌑👻🔍",
    views: 23847,
  },
  {
    id: 3155,
    title: "When the Night Falls (2025)",
    poster: "/3155id.jpg",
    trailer: "https://www.youtube.com/embed/sWtOe9DIK9o?si",
    telegramLink: "https://t.me/MoviesVerseBD/1222",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2025",
    rating: "7.3",
    language: "Japanese",
    description: "রাত নামার সঙ্গে সঙ্গে একটি শান্ত শহরে শুরু হয় অদ্ভুত সব ঘটনা। রহস্যের গভীরে যেতে গিয়ে কয়েকজন মানুষ আবিষ্কার করে তাদের নিজেদের অতীতই এই ঘটনার মূল চাবিকাঠি। 🌃🔦🔍✨",
    views: 23847,
  },
  {
    id: 3156,
    title: "Sena: Guardians of the Nation (2025) – Season 1",
    poster: "/3156id.jpg",
    trailer: "https://www.youtube.com/embed/80aiM9VFBj0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwNzgsMTUwODI",
    genre: "Action | Drama",
    year: "2025",
    rating: "7.5",
    language: "Hindi",
    description: "কাশ্মীরে সন্ত্রাসীদের হাতে বাবা-ছেলে বন্দি হওয়ার পর ভারতীয় সেনা ক্যাপ্টেন কার্তিক নিজের বাবাকে বাঁচানোর পাশাপাশি ভয়ংকর সন্ত্রাসী ষড়যন্ত্র ঠেকাতে মরিয়া হয়ে ওঠে। অতীতের দ্বন্দ্ব ভুলে দুজন মিলে শুরু করে জীবন-মরণ পালানোর লড়াই।",
    views: 23847,
  },
  {
    id: 3157,
    title: "Aashram (2020) – Season 1",
    poster: "/3157id.jpg",
    trailer: "https://www.youtube.com/embed/i5jwAKt9aLo?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwODMsMTUxMDM",
    genre: "Crime | Drama | Thriller | Mystery",
    year: "2020",
    rating: "6.6",
    language: "Hindi",
    description: "বাবা নিরালার আশ্রমে ভক্তদের ভিড় বাড়তে থাকলেও তার আধ্যাত্মিক মুখোশের আড়ালে লুকিয়ে আছে ভয়ংকর অপরাধ ও রহস্য। একটি কঙ্কাল উদ্ধারের পর পুলিশ তদন্ত শুরু করলে আশ্রমের অন্ধকার সত্য ধীরে ধীরে সামনে আসতে থাকে।",
    views: 23847,
  },
  {
    id: 3158,
    title: "Aashram (2021) – Season 2",
    poster: "/3158id.jpg",
    trailer: "https://www.youtube.com/embed/77E51-ytzrM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMDQsMTUxMjQ",
    genre: "Crime | Drama | Thriller | Mystery",
    year: "2021",
    rating: "7.1",
    language: "Hindi",
    description: "বাবা নিরালার ক্ষমতা ও প্রভাব আরও বাড়তে থাকে, কিন্তু তার আশ্রমের অন্ধকার রহস্য একে একে প্রকাশ পেতে শুরু করে। পাম্মি ও পুলিশের তদন্ত তাকে ঘিরে থাকা অপরাধের সাম্রাজ্যকে বড় বিপদের মুখে ফেলে।",
    views: 23847,
  },
  {
    id: 3159,
    title: "Korean Kanakaraju (2026)",
    poster: "/3159id.jpg",
    trailer: "https://www.youtube.com/embed/kq0X2owCVKw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMjUsMTUxMjY",
    genre: "Comedy | Fantasy | Horror",
    year: "2026",
    rating: "7.0",
    language: "Hindi",
    description: "রায়ালসীমার এক সাধারণ যুবক কানকারাজুর শরীরে কোরিয়া থেকে আসা এক আত্মা ভর করে। এরপর পরিবারকে রক্ষা ও আত্মাটির মৃত্যুর রহস্য সমাধান করতে গিয়ে শুরু হয় ভয়, হাসি আর অদ্ভুত সব ঘটনার অভিযান।",
    views: 23847,
  },
  {
    id: 3160,
    title: "Ananthan Kaadu (2026)",
    poster: "/3160id.jpg",
    trailer: "https://www.youtube.com/embed/ayderLQIP74?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMjcsMTUxMjg",
    genre: "Action | Drama | Mystery | Thriller",
    year: "2026",
    rating: "6.2",
    language: "Hindi",
    description: "রাজনৈতিক অস্থিরতা ও সংঘাতের সময়ে ক্ষমতা, প্রতিরোধ এবং টিকে থাকার লড়াইকে ঘিরে এগিয়ে যায় এক রহস্যময় গল্প। ⚔️🌲",
    views: 23847,
  },
  {
    id: 3161,
    title: "Black Box (2026)",
    poster: "/3161id.jpg",
    trailer: "https://www.youtube.com/embed/o9Wtddmq14Y?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMjksMTUxMzA",
    genre: "Horror | Sci-Fi | Thriller | Mystery",
    year: "2026",
    rating: "5.1",
    language: "Hindi",
    description: "একটি সাধারণ যাত্রাবাহী বিমান হঠাৎ অদ্ভুত ও ভয়ংকর ঘটনার মধ্যে পড়ে যায়। যাত্রীদের বাঁচার লড়াইয়ের সঙ্গে জড়িয়ে পড়ে রহস্যময় প্রযুক্তি ও ভিনগ্রহের অস্তিত্ব। ✈️👽😨",
    views: 23847,
  },
  {
    id: 3162,
    title: "Normal (2026)",
    poster: "/3162id.jpg",
    trailer: "https://www.youtube.com/embed/5OndK0w1lYY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMzEsMTUxMzI",
    genre: "Action | Crime | Thriller | Comedy",
    year: "2026",
    rating: "6.3",
    language: "Hindi",
    description: "একটি ছোট শান্ত শহরে অস্থায়ী শেরিফ হিসেবে দায়িত্ব নেওয়া Ulysses একটি ব্যাংক ডাকাতির তদন্ত করতে গিয়ে শহরের আড়ালে লুকিয়ে থাকা ভয়ংকর রহস্যের সন্ধান পায়। 🚔🏦🔍",
    views: 23847,
  },
  {
    id: 3163,
    title: "Aarata (2024)",
    poster: "/3163id.jpg",
    trailer: "https://www.youtube.com/embed/-wmyBERr-U0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMzMsMTUxMzQ",
    genre: "Biography | Drama | War | History",
    year: "2024",
    rating: "4.0",
    language: "Hindi",
    description: "দুর্গা পরমেশ্বরী মন্দিরের বার্ষিক উৎসবের পর পবিত্র একটি স্থানের দায়িত্ব ও অবহেলাকে ঘিরে গ্রামবাসীদের মধ্যে বিরোধ তৈরি হয়। এক বাবার দায়িত্বহীনতার প্রভাব ধীরে ধীরে তার পরিবার ও পুরো সম্প্রদায়ের ওপর পড়ে। 🙏🏡⚡️",
    views: 23847,
  },
  {
    id: 3164,
    title: "Tomake Holo Na Payoa (2026)",
    poster: "/3164id.jpg",
    trailer: "https://www.youtube.com/embed/e_Iu_eNUIAw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMzUsMTUxMzY",
    genre: "Crime | Drama | bangla",
    year: "2026",
    rating: "7.6",
    language: "Bangla",
    description: "ভালোবাসার মানুষকে পাওয়ার আকাঙ্ক্ষা, সম্পর্কের টানাপোড়েন আর অপূর্ণ ভালোবাসাকে ঘিরে নির্মিত একটি আবেগঘন বাংলা রোমান্টিক গল্প। ❤️🥀",
    views: 23847,
  },
  {
    id: 3165,
    title: "Zhao Yun: God of War (2022)",
    poster: "/3165id.jpg",
    trailer: "https://www.youtube.com/embed/FjVn4lmpfRg?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMzcsMTUxMzg",
    genre: "Action | War | Historical | kdrama",
    year: "2022",
    rating: "6.8",
    language: "Hindi",
    description: "প্রাচীন চীনের যুদ্ধক্ষেত্রে সাহসী যোদ্ধা ঝাও ইউন নিজের দেশ ও মানুষের জন্য ভয়ংকর যুদ্ধে ঝাঁপিয়ে পড়ে। ⚔️🏯",
    views: 23847,
  },
  {
    id: 3166,
    title: "Cocaine (2024)",
    poster: "/3166id.jpg",
    trailer: "https://www.youtube.com/embed/CDvHZCDpCY0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxMzksMTUxNDA",
    genre: "Crime | Thriller",
    year: "2024",
    rating: "6.6",
    language: "Hindi",
    description: "মুম্বাইয়ের অন্ধকার জগতে শক্তিশালী মাদকচক্র, দুর্নীতিগ্রস্ত পুলিশ ও রাজনীতির যোগসাজশকে ঘিরে শুরু হয় এক ভয়ংকর অপরাধের লড়াই। 🚔💰",
    views: 23847,
  },
  {
    id: 3167,
    title: "Women from Rote Island (2023)",
    poster: "/3167id.jpg",
    trailer: "https://www.youtube.com/embed/yd7hO9obltw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNDEsMTUxNDI",
    genre: "Drama | Thriller | Political",
    year: "2023",
    rating: "6.4",
    language: "Indonesia",
    description: "স্বামীকে হারানোর পর Orpa তার দুই মেয়েকে নিয়ে সমাজের বৈষম্য ও কঠোর প্রথার বিরুদ্ধে দাঁড়ায় এবং পরিবারের জন্য ন্যায়ের লড়াই শুরু করে। 🌺⚖️",
    views: 23847,
  },
  {
    id: 3168,
    title: "Woman of the Hour (2023)",
    poster: "/3168id.jpg",
    trailer: "https://www.youtube.com/embed/7mUEzvj3wjw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNDMsMTUxNDQ",
    genre: "netflix | Crime | Drama | Mystery | Thriller",
    year: "2023",
    rating: "6.6",
    language: "Hindi",
    description: "১৯৭০-এর দশকের একটি জনপ্রিয় ডেটিং শোতে Sheryl একজন আকর্ষণীয় ব্যাচেলরকে বেছে নেয়—কিন্তু তার পরিচয়ের আড়ালে লুকিয়ে আছে ভয়ংকর এক সত্য। 📺🔍",
    views: 23847,
  }, 
  {
    id: 3169,
    title: "Men in Hope (2011)",
    poster: "/3169id.jpg",
    trailer: "https://www.youtube.com/embed/YH9E_vqxk24?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNDUsMTUxNDY",
    genre: "Comedy | Drama | Romance",
    year: "2011",
    rating: "7.0",
    language: "Hindi",
    description: "এক শান্ত স্বভাবের জামাইকে তার শ্বশুর বিবাহিত জীবনের বাইরে প্রেমের ‘সুবিধা’ সম্পর্কে শেখাতে গিয়ে এমন পরিস্থিতি তৈরি করে, যা তাদের সম্পর্ককে জটিল করে তোলে। 😄❤️",
    views: 23847,
  },
  {
    id: 3170,
    title: "World War Z (2013)",
    poster: "/3170id.jpg",
    trailer: "https://www.youtube.com/embed/Md6Dvxdr0AQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNDcsMTUxNDg",
    genre: "Action | zombie | Horror | Sci-Fi",
    year: "2013",
    rating: "7.0",
    language: "Hindi",
    description: "পৃথিবীজুড়ে ভয়ংকর এক Zombie মহামারি ছড়িয়ে পড়লে সাবেক UN কর্মী Gerry Lane মানবজাতিকে বাঁচানোর উপায় খুঁজতে সময়ের বিরুদ্ধে ছুটে বেড়ায়। 🧟‍♂️🌍⚡️",
    views: 23847,
  },
  {
    id: 3171,
    title: "Old (2021)",
    poster: "/3171id.jpg",
    trailer: "https://www.youtube.com/embed/NcMKhpugdQE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNDksMTUxNTA",
    genre:  "Mystery | Thriller | Drama | Horror",
    year: "2021",
    rating: "5.8",
    language: "Hindi",
    description: "ছুটিতে যাওয়া একটি পরিবার নির্জন সমুদ্রসৈকতে আটকা পড়ে আবিষ্কার করে যে সেখানে তারা অস্বাভাবিক দ্রুত বয়স বাড়তে থাকে—মাত্র কয়েক ঘণ্টার মধ্যেই জীবন যেন এক দিনে শেষ হয়ে যাচ্ছে। 🏖️⏳😨",
    views: 23847,
  },
  {
    id: 3172,
    title: "S.R. Kalyanamandapam (2021)",
    poster: "/3172id.jpg",
    trailer: "https://www.youtube.com/embed/FQ5bBHGlLLU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNTEsMTUxNTI",
    genre: "Drama | Romance | Comedy",
    year: "2021",
    rating: "6.1",
    language: "Hindi",
    description: "একজন তরুণের প্রেম, পরিবার এবং বাবার সঙ্গে তার জটিল সম্পর্ককে ঘিরে গল্প এগিয়ে যায়। ভালোবাসা ও পারিবারিক মূল্যবোধের মধ্যে নিজের জায়গা খুঁজে নেওয়ার চেষ্টা করে সে। ❤️👨‍👦💫",
    views: 23847,
  },
  {
    id: 3173,
    title: "Iravukku Aayiram Kangal (2018)",
    poster: "/3173id.jpg",
    trailer: "https://www.youtube.com/embed/qmUkTtEa_nc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNTMsMTUxNTQ",
    genre: "Action | Crime | Thriller",
    year: "2018",
    rating: "7.3",
    language: "Hindi",
    description: "একটি রহস্যময় হত্যাকাণ্ডকে ঘিরে শান্ত স্বভাবের ক্যাবচালক ভারত এবং ব্ল্যাকমেইলকারী গণেশের জীবন এক জটিল খেলায় জড়িয়ে পড়ে। সত্য উদঘাটনের সঙ্গে সঙ্গে রহস্য আরও গভীর হতে থাকে। 🚕🔍🩸",
    views: 23847,
  },
  {
    id: 3174,
    title: "The Book of Sijjin and Illiyyin (2025)with bangla subtitle☑️",
    poster: "/3174id.jpg",
    trailer: "https://www.youtube.com/embed/orZrOvDrGXk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNTUsMTUxNTc",
    genre: "Horror | Thriller | Supernatural",
    year: "2024",
    rating: "6.3",
    language: "Indonesian",
    description: "নির্যাতিত ইউলি প্রতিশোধের নেশায় নিষিদ্ধ কালোজাদুর আশ্রয় নেয়। সেই অন্ধকার আচার শুরু হওয়ার পর তার পরিবার একের পর এক ভয়ংকর অতিপ্রাকৃত ঘটনার মুখোমুখি হয়। 👻🕯️😨",
    views: 23847,
  },
  {
    id: 3175,
    title: "Tula Pahata (2026)",
    poster: "/3175id.jpg",
    trailer: "https://www.youtube.com/embed/DXdtGatrVPY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNTgsMTUxNTk",
    genre: "kdrama | Fantasy | Romance | Action | Historical",
    year: "2026",
    rating: "7.7",
    language: "Hindi",
    description: "এক সুরকার ও দাবা গ্র্যান্ডমাস্টার সামাজিক প্রচলিত নিয়মকে উপেক্ষা করে একসঙ্গে থাকার সিদ্ধান্ত নেয়। এরপর দুই পরিবারের মিলন তাদের পুরোনো গোপনীয়তা ও সম্পর্কের নানা জটিলতা সামনে নিয়ে আসে। ",
    views: 23847,
  },
  {
    id: 3176,
    title: "Last Days (2025)",
    poster: "/3176id.jpg",
    trailer: "https://www.youtube.com/embed/18m3rC2mgE8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNjAsMTUxNjE",
    genre: "Biography | Drama | Adventure | Docudrama",
    year: "2025",
    rating: "5.0",
    language: "Hindi",
    description: "একজন তরুণ মিশনারি বিচ্ছিন্ন একটি দ্বীপের আদিবাসী জনগোষ্ঠীর কাছে পৌঁছানোর চেষ্টা করে। তার উদ্দেশ্য ও স্থানীয় পরিস্থিতিকে ঘিরে শুরু হয় এক বিপজ্জনক ও বিতর্কিত যাত্রা। 🌊🏝️⚠️",
    views: 23847,
  },
  {
    id: 3177,
    title: "DCP Shankar – The Destroyer (2026)",
    poster: "/3177id.jpg",
    trailer: "https://www.youtube.com/embed/vZhHrL68h_g?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNjIsMTUxNjM",
    genre: "Action | Crime | Thriller",
    year: "2026",
    rating: "7.2",
    language: "Hindi",
    description: "একজন কঠোর পুলিশ কর্মকর্তা অপরাধী চক্রের বিরুদ্ধে অভিযান চালাতে গিয়ে নিজের দায়িত্ব, ন্যায়বিচার ও বিপজ্জনক শত্রুদের মুখোমুখি হয়। 🚔⚡️",
    views: 23847,
  },
  {
    id: 3178,
    title: "Drawn Together – Enfrentados: Marfil (2026)",
    poster: "/3178id.jpg",
    trailer: "https://www.youtube.com/embed/QdZrKlM5QUQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNjQsMTUxNjU",
    genre: "Romance | Drama | Thriller",
    year: "2026",
    rating: "8.8",
    language: "Hindi",
    description: "অপহরণের পর ধনী তরুণী Marfil-এর নিরাপত্তার দায়িত্ব নেয় তার দেহরক্ষী Sebastian। দুই বিপরীত স্বভাবের মানুষের মধ্যে ধীরে ধীরে তৈরি হয় এক জটিল সম্পর্ক, যার সঙ্গে জড়িয়ে থাকে গোপন রহস্য ও বিপদ। ❤️🔐⚡️",
    views: 23847,
  },
  {
    id: 3179,
    title: "Dexter (2025)",
    poster: "/3179id.jpg",
    trailer: "https://www.youtube.com/embed/84o1Q6fB20k?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNjYsMTUxNjc",
    genre: "Crime | Drama | Mystery | Thriller",
    year: "2025",
    rating: "9.0",
    language: "Hindi",
    description: "কোমা থেকে জেগে ওঠার পর Dexter তার ছেলে Harrison-কে খুঁজতে নিউইয়র্কে যায়। কিন্তু পুরোনো পরিচিতরা ফিরে আসায় তার অতীত আবারও সামনে চলে আসে। 🕵️‍♂️🌃",
    views: 23847,
  },
  {
    id: 3180,
    title: "Parthenope (2024)",
    poster: "/3180id.jpg",
    trailer: "https://www.youtube.com/embed/uT5PGHBugic?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNjgsMTUxNjk",
    genre: "Coming-of-Age | Drama | Fantasy",
    year: "2024",
    rating: "6.5",
    language: "Hindi",
    description: "১৯৫০ সালের নেপলসে জন্ম নেওয়া Parthenope তার যৌবনের দীর্ঘ গ্রীষ্মগুলোতে ভালোবাসা, স্বাধীনতা ও জীবনের অর্থ খুঁজতে থাকে। একইসঙ্গে তার প্রিয় শহর ও মানুষের সঙ্গে গড়ে ওঠে গভীর সম্পর্ক। 🌊🇮🇹✨",
    views: 23847,
  },
  {
    id: 3181,
    title: "Sleep Tight (2011)",
    poster: "/3181id.jpg",
    trailer: "https://www.youtube.com/embed/hYAPKHQtdmU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNzAsMTUxNzE",
    genre: "Thriller | Horror | Drama | Crime",
    year: "2011",
    rating: "7.2",
    language: "Spanish",
    description: "একটি অ্যাপার্টমেন্টের কেয়ারটেকার César বাসিন্দাদের জীবন সম্পর্কে অত্যন্ত আগ্রহী। এক তরুণী বাসিন্দাকে কেন্দ্র করে তার অন্ধকার মানসিকতা ও গোপন কর্মকাণ্ড ভয়ংকর পরিস্থিতির জন্ম দেয়। 🏢😨🔍",
    views: 23847,
  },
  {
    id: 3182,
    title: "The Happening (2008)",
    poster: "/3182id.jpg",
    trailer: "https://www.youtube.com/embed/TJ71uf635hM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNzIsMTUxNzM",
    genre: "Sci-Fi | Thriller | Mystery | Horror",
    year: "2008",
    rating: "5.0",
    language: "English",
    description: "হঠাৎ করে অজানা এক প্রাকৃতিক ঘটনা মানুষের আচরণকে ভয়ংকরভাবে বদলে দিতে শুরু করে। শিক্ষক Elliot তার স্ত্রী ও এক বন্ধুর সঙ্গে এই রহস্যময় বিপর্যয় থেকে বাঁচার চেষ্টা করে এবং এর কারণ খুঁজতে থাকে। 🌿🌪️😨",
    views: 23847,
  },
  {
    id: 3183,
    title: "Hounddog (2007)",
    poster: "/3183id.jpg",
    trailer: "https://www.youtube.com/embed/NcXbhuOOsuk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNzQsMTUxNzU",
    genre: "Coming-of-Age | Drama | Music",
    year: "2007",
    rating: "6.2",
    language: "English",
    description: "১৯৫০-এর দশকের আমেরিকান দক্ষিণাঞ্চলে এক কিশোরী কঠিন পারিবারিক পরিস্থিতির মাঝেও Elvis Presley-এর সংগীতের মধ্যে নিজের জন্য আশ্রয় ও সাহস খুঁজে পায়। 🎵🌻",
    views: 23847,
  },
  {
    id: 3184,
    title: "Faithfully Yours (2022)",
    poster: "/3184id.jpg",
    trailer: "https://www.youtube.com/embed/fsB4B-DTOWs?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNzYsMTUxNzc",
    genre: "Crime | Mystery | Thriller | netflix",
    year: "2022",
    rating: "5.8",
    language: "Hindi",
    description: "দুই ঘনিষ্ঠ বান্ধবী নিজেদের গোপন সম্পর্ক লুকাতে একে অপরকে অ্যালিবি হিসেবে ব্যবহার করে। কিন্তু একজন খুন হওয়ার পর তাদের সাজানো মিথ্যার জাল ভয়ংকরভাবে জটিল হয়ে ওঠে। 🔍🕵️‍♀️",
    views: 23847,
  },
  {
    id: 3185,
    title: "Nar'sata: Sekutu Setan (2026)",
    poster: "/3185id.jpg",
    trailer: "https://www.youtube.com/embed/eO91EVN7ITM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxNzgsMTUxNzk",
    genre: "Horror | Thriller",
    year: "2026",
    rating: "5.7",
    language: "English",
    description: "বিশ্বাসঘাতকতা ও কষ্টে বড় হয়ে ওঠা Balqis প্রতিশোধের জন্য অন্ধকার এক পথ বেছে নেয়। কিন্তু প্রতিশোধের সেই সিদ্ধান্তের ভয়ংকর মূল্য তাকে ধীরে ধীরে বুঝতে হয়। 👻🕯️",
    views: 23847,
  },
  {
    id: 3186,
    title: "Puratawn (2025)",
    poster: "/3186id.jpg",
    trailer: "https://www.youtube.com/embed/-iHJyTxQpS4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxODAsMTUxODE",
    genre: "Musical | Drama | Romance | bangla",
    year: "2025",
    rating: "6.8",
    language: "Bangla",
    description: "মায়ের ৮০তম জন্মদিনে পুরোনো বাড়িতে ফিরে Ritika আবিষ্কার করে, তার মায়ের স্মৃতি ও মানসিক অবস্থার দ্রুত অবনতি ঘটছে। অতীত ও বর্তমানের স্মৃতির টানাপোড়েনে পরিবারকে কঠিন বাস্তবতার মুখোমুখি হতে হয়। 🏡💭❤️",
    views: 23847,
  },
  {
    id: 3187,
    title: "Ghamasaan (2026)",
    poster: "/3187id.jpg",
    trailer: "https://www.youtube.com/embed/OEvaXgDTPmU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxODIsMTUxODM",
    genre: "Action | Drama",
    year: "2026",
    rating: "6.8",
    language: "Hindi",
    description: "IPS কর্মকর্তা Aditya Singh ভয়ংকর এক ডাকাতকে ধরতে অভিযানে নামে। নিয়মের সীমা ও নিজের বুদ্ধিকে কাজে লাগিয়ে তাকে অপরাধী ও দুর্নীতির বিরুদ্ধে কঠিন লড়াইয়ে নামতে হয়। 🚔🔥⚔️",
    views: 23847,
  },
  {
    id: 3188,
    title: "Pinocchio: Unstrung (2026)",
    poster: "/3188id.jpg",
    trailer: "https://www.youtube.com/embed/uApioBmGpAc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxODQsMTUxODU",
    genre: "Horror | Fantasy | Thriller",
    year: "2026",
    rating: "5.4",
    language: "Hindi",
    description: "পরিচিত Pinocchio গল্পকে অন্ধকার হরর রূপে দেখানো হয়েছে, যেখানে জীবন্ত হয়ে ওঠা পুতুলটি নিজেকে সত্যিকারের মানুষে পরিণত করার পথে ভয়ংকর এক যাত্রায় জড়িয়ে পড়ে। 🪵👹❤️✨",
    views: 23847,
  },
  {
    id: 3189,
    title: "Pitt Siyapa (2026)",
    poster: "/3189id.jpg",
    trailer: "https://www.youtube.com/embed/G6Oi73J8Lc4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxODYsMTUxODc",
    genre: "Comedy | Drama | Romance",
    year: "2026",
    rating: "6.9",
    language: "Hindi",
    description: "Nimmi বাবার মৃত্যুর পর প্রবাসীদের জন্য ভার্চুয়াল অন্ত্যেষ্টিক্রিয়ার ব্যবসা শুরু করে। কিন্তু NRI Mickey-এর আগমনের পর ভুল পরিচয়, বিশৃঙ্খলা ও অপ্রত্যাশিত প্রেমে তাদের জীবন পুরোপুরি পাল্টে যায়। 😂❤️🎭",
    views: 23847,
  },
  {
    id: 3190,
    title: "Vishwanath & Sons (2026)",
    poster: "/3190id.jpg",
    trailer: "https://www.youtube.com/embed/95xXBEsmWLU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxODgsMTUxODk",
    genre: "Drama | Family | Romance | Sport",
    year: "2026",
    rating: "7.6",
    language: "Hindi",
    description: "আন্তর্জাতিক শুটার Sanjay Vishwanath জীবনের বড় একটি অংশ সাফল্যের পেছনে কাটিয়েছে। বয়স, পারিবারিক দায়িত্ব ও অপ্রত্যাশিত এক প্রেম তার সামনে নতুন প্রশ্ন তুলে দেয়—জীবনে আসলে কোন বিষয়গুলো সবচেয়ে গুরুত্বপূর্ণ। 🏆❤️👨‍👩‍👦",
    views: 23847,
  },
  {
    id: 3191,
    title: "Maharaja Hostel (2026)",
    poster: "/3191id.jpg",
    trailer: "https://www.youtube.com/embed/dsTcSWWE2Ug?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxOTAsMTUxOTE",
    genre: "Comedy | Horror",
    year: "2026",
    rating: "7.2",
    language: "Hindi",
    description: "শহরের একটি অদ্ভুত হোস্টেল, রহস্যময় ওয়ার্ডেন MGR এবং সেখানে থাকা কয়েকজন বন্ধুকে ঘিরে শুরু হয় হাস্যরস ও ভৌতিক ঘটনার মিশেল। 🏨👻😂",
    views: 23847,
  },
  {
    id: 3192,
    title: "Salmokji: Whispering Water (2026)",
    poster: "/3192id.jpg",
    trailer: "https://www.youtube.com/embed/FQ557PpoKpo?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxOTIsMTUxOTM",
    genre: "Horror | Mystery | Thriller | kdrama",
    year: "2026",
    rating: "8.9",
    language: "Hindi",
    description: "একটি ফিল্মিং টিম পুরোনো ফুটেজের রহস্যজনক সমস্যার কারণে প্রত্যন্ত এক জলাধারে ফিরে যায়। সেখানে ক্যামেরায় ধরা পড়ে এমন কিছু, যা তাদের কেউ শুটিংয়ের সময় দেখেনি—আর জলাধারের অতীতের অমীমাংসিত রহস্য সামনে আসতে থাকে। 🌊👻🎥",
    views: 23847,
  },
  {
    id: 3193,
    title: "Roy (2015)",
    poster: "/3193id.jpg",
    trailer: "https://www.youtube.com/embed/ahz3kTiGo3s?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxOTQsMTUxOTU",
    genre: "Action | Romance | Thriller",
    year: "2015",
    rating: "3.3",
    language: "Hindi",
    description: "এক চলচ্চিত্র নির্মাতা তার নতুন সিনেমার গল্প ও বাস্তব জীবনের সম্পর্কের মধ্যে জড়িয়ে পড়ে। এদিকে রহস্যময় চোর রয় তার জীবনে এসে ভালোবাসা, প্রতারণা ও অপরাধের জটিলতা আরও বাড়িয়ে দেয়।",
    views: 23847,
  },
    {
    id: 3194,
    title: "Panic Room (2002)",
    poster: "/3194id.jpg",
    trailer: "https://www.youtube.com/embed/sp2kKzrCm44?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxOTYsMTUxOTc",
    genre: "Crime | Drama | Thriller",
    year: "2002",
    rating: "6.8",
    language: "Hindi",
    description: "নতুন বাড়িতে ওঠার পর মা ও মেয়ে ডাকাতদের আক্রমণের শিকার হয়। তারা বাড়ির সুরক্ষিত Panic Room-এ আশ্রয় নিলেও পরিস্থিতি ধীরে ধীরে আরও বিপজ্জনক হয়ে ওঠে। 🏠🔐😨",
    views: 23847,
  },
  {
    id: 3195,
    title: "Haiwaan (2026)",
    poster: "/3195id.jpg",
    trailer: "https://www.youtube.com/embed/Bm5S7ZKk6K8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUxOTgsMTUxOTk",
    genre: "Action | Thriller | Crime",
    year: "2026",
    rating: "6.8",
    language: "Hindi",
    description: "অপরাধ ও প্রতিশোধের অন্ধকার জগতকে ঘিরে এক ভয়ংকর সংঘাতের গল্প। ⚡️🚔",
    views: 23847,
  },
  {
    id: 3196,
    title: "2nd Chorki Carnival (2026)",
    poster: "/3196id.jpg",
    trailer: "https://www.youtube.com/embed/VcKKXefDyc8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMDAsMTUyMDE",
    genre: "Anthology | Drama | Thriller | bangla",
    year: "2026",
    rating: "6.9",
    language: "Bangla",
    description: "Chorki-এর বিশেষ কনটেন্ট আয়োজনকে ঘিরে বিভিন্ন গল্প ও চরিত্রের সমন্বয়ে তৈরি একটি বিনোদনমূলক সংকলন। 🎭🎬",
    views: 23847,
  },
  {
    id: 3197,
    title: "The Returned (2013)",
    poster: "/3197id.jpg",
    trailer: "https://www.youtube.com/embed/B6h5vtY5qZU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMDIsMTUyMDM",
    genre: "Drama | Fantasy | Horror | Mystery",
    year: "2013",
    rating: "6.9",
    language: "Hindi",
    description: "বহু বছর আগে মারা যাওয়া কয়েকজন মানুষ হঠাৎ জীবিত অবস্থায় নিজেদের শহরে ফিরে আসে। তাদের প্রত্যাবর্তন পুরো সম্প্রদায়ের জীবনে রহস্য ও অস্বস্তির সৃষ্টি করে। 🏚️👤🌫️",
    views: 23847,
  },
  {
    id: 3198,
    title: "The Prison (2017)",
    poster: "/3198id.jpg",
    trailer: "https://www.youtube.com/embed/WFoLR2ARyBY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMDQsMTUyMDU",
    genre: "Action | Crime | Thriller",
    year: "2017",
    rating: "6.5",
    language: "Hindi",
    description: "একজন সাবেক পুলিশ কর্মকর্তা কারাগারে ঢুকে সেখানে বন্দিদের সঙ্গে মিলে বাইরে অপরাধ পরিচালনা করা এক শক্তিশালী অপরাধচক্রের রহস্য উন্মোচন করে। 🔒⚡️",
    views: 23847,
  },
  {
    id: 3199,
    title: "Fist of Fury: Soul (2021)",
    poster: "/3199id.jpg",
    trailer: "https://www.youtube.com/embed/eLEMKNPajco?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMDYsMTUyMDc",
    genre: "Action | Martial Arts | kdrama",
    year: "2021",
    rating: "8.3",
    language: "Chinese",
    description: "মার্শাল আর্টের দক্ষতা, সম্মান ও প্রতিশোধকে ঘিরে এক যোদ্ধার কঠিন লড়াইয়ের গল্প। 🥋🔥",
    views: 23847,
  },
  {
    id: 3200,
    title: "Keno Ei Shongota (2026)",
    poster: "/3200id.jpg",
    trailer: "https://www.youtube.com/embed/J5kvK_74mtE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMDgsMTUyMDk",
    genre: "Drama | Romance | bangla",
    year: "2026",
    rating: "6.3",
    language: "Bangla",
    description: "সম্পর্ক, ভালোবাসা ও জীবনের কঠিন বাস্তবতার টানাপোড়েনকে ঘিরে এগিয়ে যায় আবেগঘন একটি বাংলা গল্প। ❤️🥀",
    views: 23847,
  },
  {
    id: 3201,
    title: "Khalifa (2026)",
    poster: "/3201id.jpg",
    trailer: "https://www.youtube.com/embed/8NiMCt2o-uQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMTAsMTUyMTE",
    genre: "Drama | Thriller",
    year: "2026",
    rating: "7.8",
    language: "Hindi",
    description: "ক্ষমতা, পরিচয় ও প্রতিকূলতার মাঝে নিজের অবস্থান তৈরি করার লড়াইকে কেন্দ্র করে গল্পটি এগিয়ে যায়। ⚔️🔥",
    views: 23847,
  },
  {
    id: 3202,
    title: "Grihostho (2025)",
    poster: "/3202id.jpg",
    trailer: "https://www.youtube.com/embed/6HTjp-ST25Y?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMTIsMTUyMTM",
    genre: "Drama | Family | Thriller | bangla",
    year: "2025",
    rating: "6.4",
    language: "Bangla",
    description: "একটি পরিবারের ঘরোয়া জীবনের আড়ালে জমে থাকা সম্পর্কের টানাপোড়েন, গোপন সত্য ও আবেগ ধীরে ধীরে সামনে আসে। 🏠💔",
    views: 23847,
  },
  {
    id: 3203,
    title: "Irumudi (2026)",
    poster: "/3203id.jpg",
    trailer: "https://www.youtube.com/embed/CSXhb2zhfLc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMTQsMTUyMTU",
    genre: "Drama | Thriller",
    year: "2026",
    rating: "6.4",
    language: "Hindi",
    description: "বিশ্বাস, যাত্রা ও ব্যক্তিগত সংঘাতকে ঘিরে এক চরিত্রের কঠিন পথচলার গল্প। 🙏🔥🎭",
    views: 23847,
  },
  {
    id: 3204,
    title: "Hope (2026)",
    poster: "/3204id.jpg",
    trailer: "https://www.youtube.com/embed/5zlfPKPmAjM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMTYsMTUyMTc",
    genre: "Horror | Action | Mystery | Sci-Fi | Thriller | kdrama",
    year: "2026",
    rating: "6.9",
    language: "Korean",
    description: "দক্ষিণ কোরিয়ার Hope Harbor নামের প্রত্যন্ত এলাকায় রহস্যময় এক প্রাণীর আবির্ভাবের পর পুরো শহর আতঙ্ক ও বিশৃঙ্খলায় ডুবে যায়। পুলিশ, স্থানীয় শিকারি ও সাধারণ মানুষ অজানা সেই প্রাণীর বিরুদ্ধে বাঁচার লড়াইয়ে নেমে পড়ে। 👽🌲🏃‍♂️😨",
    views: 23847,
  },
    {
    id: 3205,
    title: "The Unspoken Secret (2025)",
    poster: "/3205id.jpg",
    trailer: "https://www.youtube.com/embed/YsVo5necW6Q?si",
    telegramLink: "https://t.me/MoviesVerseBD/1224",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2025",
    rating: "6.7",
    language: "Japanese",
    description: "একটি অপ্রত্যাশিত ঘটনার পর বহুদিনের লুকিয়ে থাকা এক সত্য ধীরে ধীরে প্রকাশ পেতে শুরু করে। অতীতের রহস্য উন্মোচনের সঙ্গে সঙ্গে বদলে যেতে থাকে কয়েকজন মানুষের জীবন। 🌙🔍✨",
    views: 23847,
  },
  {
    id: 3206,
    title: "Latina (2026)",
    poster: "/3206id.jpg",
    trailer: "https://www.youtube.com/embed/yImcF_Jy8Jc?si",
    telegramLink: "https://t.me/MoviesVerseBD/1229",
    genre: "Adult | Drama | Mystery | Romance",
    year: "2026",
    rating: "7.4",
    language: "Filipino",
    description: "এক তরুণী তার জীবনের কঠিন পরিস্থিতি থেকে বেরিয়ে আসতে এবং নিজের পরিচয় খুঁজে পেতে নানা চ্যালেঞ্জ ও প্রলোভনের মুখোমুখি হয়।",
    views: 23847,
  },
  {
    id: 3207,
    title: "Christine Bermas All The Way (2026)",
    poster: "/3207id.jpg",
    trailer: "https://www.youtube.com/embed/kFGxuWBZPtw?si",
    telegramLink: "https://t.me/MoviesVerseBD/1231",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2026",
    rating: "5.8",
    language: "Filipino",
    description: "জনপ্রিয় অভিনেত্রী ক্রিস্টিন বারমাসের জীবনের নানা রোমাঞ্চকর ও সাহসী চরিত্রের গল্প নিয়ে তৈরি একটি বিশেষ সংকলন।",
    views: 23847,
  }, 
  {
    id: 3208,
    title: "Hibla 2 (2026)",
    poster: "/3208id.jpg",
    trailer: "https://www.youtube.com/embed/8Jb4yjbo8EQ?si",
    telegramLink: "https://t.me/MoviesVerseBD/1233",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2026",
    rating: "6.6",
    language: "Filipino",
    description: "গোপন সম্পর্ক ও পারিবারিক জটিলতার আবর্তে জড়িয়ে পড়া কয়েকজন মানুষের আবেগ ও বিশ্বাসঘাতকতার গল্প।",
    views: 23847,
  },
  {
    id: 3209,
    title: "The Cheating Wife (2026)",
    poster: "/3209id.jpg",
    trailer: "https://www.youtube.com/embed/iVOyYHzvbKc?si",
    telegramLink: "https://t.me/MoviesVerseBD/1235",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2026",
    rating: "5.4",
    language: "Filipino",
    description: "এক বিবাহিত নারী তার স্বামীর অবহেলার কারণে পরকীয়ায় জড়িয়ে পড়ে, যা পরবর্তীতে তার ব্যক্তিগত জীবনে মারাত্মক সংকট ডেকে আনে।",
    views: 23847,
  },
  {
    id: 3210,
    title: "Helena (2026)",
    poster: "/3210id.jpg",
    trailer: "https://www.youtube.com/embed/ra1lR1-zPD4?si",
    telegramLink: "https://t.me/MoviesVerseBD/1238",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2026",
    rating: "7.3",
    language: "Filipino",
    description: "হেলেনা নামের এক রহস্যময় নারীর অতীত জীবনের গোপন সত্য এবং তার জীবনে আসা নতুন প্রেমের টানাপোড়েনের কাহিনী।" ,
    views: 23847,
  },
  {
    id: 3211,
    title: "Lunok (2026)",
    poster: "/3211id.jpg",
    trailer: "https://www.youtube.com/embed/gA8I-JbixOE?si",
    telegramLink: "https://t.me/MoviesVerseBD/1240",
    genre: "Adult | Drama | Mystery | Romance",
    year: "2026",
    rating: "5.6",
    language: "Filipino",
    description: "ভালোবাসা ও শারীরিক আকর্ষণের মাঝে পড়ে নিজের আবেগ ও সততাকে বিসর্জন দেওয়ার এক বাস্তবধর্মী গল্প।",
    views: 23847,
  },
  {
    id: 3212,
    title: "Ang Modista (2026)",
    poster: "/3212id.jpg",
    trailer: "https://www.youtube.com/embed/HjOBFyYnilw?si",
    telegramLink: "https://t.me/MoviesVerseBD/1242",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2026",
    rating: "6.4",
    language: "Filipino",
    description: "এক পোশাক দর্জির জীবনকে কেন্দ্র করে আবর্তিত গল্প, যেখানে গ্ল্যামারের আড়ালে লুকিয়ে থাকা লালসা ও প্রতিহিংসা ফুটে ওঠে।",
    views: 23847,
  },
  {
    id: 3213,
    title: "Siping (2026)",
    poster: "/3213id.jpg",
    trailer: "https://www.youtube.com/embed/q6qSIxYgSdc?si",
    telegramLink: "https://t.me/MoviesVerseBD/1244",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2026",
    rating: "6.3",
    language: "Filipino",
    description: "এক ছাদের নিচে কাটানো নিবিড় মুহূর্ত এবং ভালোবাসার গোপন সম্পর্কের আবেগঘন পরিবেশনা।",
    views: 23847,
  },
  {
    id: 3214,
    title: "Creampie (2026)",
    poster: "/3214id.jpg",
    trailer: "https://www.youtube.com/embed/bRYZEdtPKfs?si",
    telegramLink: "https://t.me/MoviesVerseBD/1246",
    genre: "Adult | Mystery | Drama | Thriller",
    year: "2026",
    rating: "5.9",
    language: "Filipino",
    description: "জটিল সম্পর্ক ও রোমান্টিক জীবনের নানা মজাদার ও সংবেদনশীল মুহূর্তের মধ্য দিয়ে এগিয়ে যাওয়া একটি গল্প।",
    views: 23847,
  },
  {
    id: 3215,
    title: "Pinay Kamasutra (2026)",
    poster: "/3215id.jpg",
    trailer: "https://www.youtube.com/embed/u7Jcc_ug2gs?si",
    telegramLink: "https://t.me/MoviesVerseBD/1248",
    genre: "Adult | Mystery | Thriller | Drama",
    year: "2026",
    rating: "4.9",
    language: "Filipino",
    description: "ফিলিপিনো আধুনিক জীবনের সম্পর্কের রসায়ন, ইচ্ছা ও শারীরিক সম্পর্কের নানা দিক নিয়ে নির্মিত একটি সিনেমা।",
    views: 23847,
  },
  {
    id: 3216,
    title: "Haplos Ni Milagros (2026)",
    poster: "/3216id.jpg",
    trailer: "https://www.youtube.com/embed/FBP_zQQK2vU?si",
    telegramLink: "https://t.me/MoviesVerseBD/1250",
    genre: "Adult | Mystery | Horror | Thriller",
    year: "2026",
    rating: "6.4",
    language: "Filipino",
    description: "মিলাগ্রোস নামের এক নারীর স্পর্শে লুকিয়ে থাকা রহস্য, আকুলতা এবং তার জীবনের জটিল সম্পর্কের টানাপোড়েনের গল্প।",
    views: 23847,
  },
  {
    id: 3217,
    title: "Spit Or Swallow (2026)",
    poster: "/3217id.jpg",
    trailer: "https://www.youtube.com/embed/xaqWknnYnLo?si",
    telegramLink: "https://t.me/MoviesVerseBD/1252",
    genre: "Adult | Drama | Mystery | Thriller",
    year: "2026",
    rating: "7.3",
    language: "Filipino",
    description: "আধুনিক সম্পর্কের নানা দ্বিমুখী সংকট, সিদ্ধান্তহীনতা এবং প্রলোভনের মুখোমুখি হওয়া কয়েকজন তরুণের জীবনকাহিনী।",
    views: 23847,
  },
  {
    id: 3218,
    title: "Magudam (2026)",
    poster: "/3218id.jpg",
    trailer: "https://www.youtube.com/embed/jEAQp6jjmQA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMjAsMTUyMjE",
    genre: "Action | Drama | Thriller",
    year: "2026",
    rating: "5.4",
    language: "Hindi",
    description: "সমুদ্রের ঢেউয়ের মাঝে জন্ম নেওয়া এক প্রেম বিশ্বাসঘাতকতায় ধ্বংস হয়ে যায়। এরপর প্রতিশোধের এক ভয়ংকর যাত্রা শুরু হয়, যা ধীরে ধীরে সবাইকে বিপদের মুখে ঠেলে দেয়। 🌊💔🔥",
    views: 23847,
  },
  {
    id: 3219,
    title: "Hen (2026)",
    poster: "/3219id.jpg",
    trailer: "https://www.youtube.com/embed/Zd9CGEUsIFA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMjIsMTUyMjM",
    genre: "Animal | Adventure | Drama | Comedy | Thriller",
    year: "2026",
    rating: "7.0",
    language: "Hindi",
    description: "একটি মুরগির দৃষ্টিকোণ থেকে বলা গল্পে, একটি গ্রিক সমুদ্রতীরবর্তী রেস্টুরেন্টে আশ্রয় নেওয়া পলাতক এক ব্যক্তির জীবন ও চারপাশের মানুষের জটিলতা ফুটে ওঠে। 🐔🌊🍽️",
    views: 23847,
  },
  {
    id: 3220,
    title: "Area 51 (2015)",
    poster: "/3220id.jpg",
    trailer: "https://www.youtube.com/embed/JUhYHG0zXS0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMjQsMTUyMjU",
    genre: "Horror | Mystery | Sci-Fi | Thriller | Found Footage",
    year: "2015",
    rating: "4.3/",
    language: "Hindi",
    description: "তিনজন conspiracy theorist গোপন Area 51-এ ঢুকে এলিয়েন-সংক্রান্ত রহস্যের সন্ধান করতে যায়। কিন্তু সেখানে তারা এমন ভয়ংকর সত্যের মুখোমুখি হয়, যা তাদের কল্পনারও বাইরে। 👽🔬😨",
    views: 23847,
  },
  {
    id: 3221,
    title: "Kabir Azabi: Insi ve Cinni (2024)",
    poster: "/3221id.jpg",
    trailer: "https://www.youtube.com/embed/Et3R-hXCKIw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMjYsMTUyMjc",
    genre: "Drama | Fantasy | Horror | Mystery",
    year: "2024",
    rating: "3.5",
    language: "Turkish",
    description: "স্বামী Muhsin-এর মৃত্যুকে মেনে নিতে না পেরে Nejla এক মাধ্যমের সাহায্য নেয়। অতিপ্রাকৃত শক্তির আশায় সে এমন এক সিদ্ধান্ত নেয়, যা তার জীবনে ভয়ংকর পরিণতি ডেকে আনে। 🕯️👻💀",
    views: 23847,
  },
  {
    id: 3222,
    title: "Hungry (2026)",
    poster: "/3222id.jpg",
    trailer: "https://www.youtube.com/embed/QX85JymdGnQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMjgsMTUyMjk",
    genre: "Horror | Mystery | Thriller",
    year: "2026",
    rating: "5.0",
    language: "Hindi",
    description: "লুইজিয়ানার জলাভূমিতে ঘুরতে গিয়ে একদল পর্যটক পথ হারিয়ে ফেলে। এরপর তারা একটি ভয়ংকর জলহস্তীর মুখোমুখি হয়ে প্রাণ বাঁচানোর লড়াইয়ে পড়ে যায়। 🐊🌿😨",
    views: 23847,
  },
  {
    id: 3223,
    title: "Mandaadi (2026)",
    poster: "/3223id.jpg",
    trailer: "https://www.youtube.com/embed/VOHaf-0DV-U?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMzAsMTUyMzE",
    genre: "Action | Drama | Sports | Adventure",
    year: "2026",
    rating: "7.6",
    language: "Chinese",
    description: "তামিলনাড়ুর উপকূলে এক ঐতিহ্যবাহী নৌকা প্রতিযোগিতায় ছয় সদস্যের দলকে নেতৃত্ব দেয় এক অভিজ্ঞ জেলে। প্রতিদ্বন্দ্বী দলের সঙ্গে তীব্র প্রতিযোগিতার মধ্য দিয়ে উঠে আসে সাহস, দলগত ঐক্য ও সমুদ্রজয়ের গল্প। 🌊🚣‍♂️",
    views: 23847,
  },
  {
    id: 3224,
    title: "Fanletter, Please (2022) – Season 1",
    poster: "/3224id.jpg",
    trailer: "https://www.youtube.com/embed/9YTeauMwOQs?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyMzIsMTUyNTA",
    genre: "kdrama | Romance | Comedy | Drama",
    year: "2022",
    rating: "7.0",
    language: "Hindi",
    description: "এক জনপ্রিয় অভিনেত্রী তার ভক্তের চিঠির উত্তর দিতে গিয়ে এক পুরোনো পরিচিত মানুষের সঙ্গে আবারও জড়িয়ে পড়ে। ছোট্ট একটি চিঠি তাদের জীবনে ফিরিয়ে আনে পুরোনো অনুভূতি ও নতুন ভালোবাসা।",
    views: 23847,
  },
  {
    id: 3225,
    title: "Udaipur Files: A Tailor's Murder Story (2025)",
    poster: "/3225id.jpg",
    trailer: "https://www.youtube.com/embed/8UgzqNmghMY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyNTEsMTUyNTI",
    genre: "Crime | Drama | Thriller",
    year: "2025",
    rating: "5.4",
    language: "Hindi",
    description: "উদয়পুরে ঘটে যাওয়া এক চাঞ্চল্যকর হত্যাকাণ্ডের ঘটনা ও তার পরবর্তী তদন্তকে কেন্দ্র করে গল্পটি এগিয়ে যায়। ধর্মীয় উত্তেজনা, অপরাধ ও ন্যায়বিচারের প্রশ্নে পরিস্থিতি আরও জটিল হয়ে ওঠে। 🔍⚖️🔥",
    views: 23847,
  },
  {
    id: 3226,
    title: "Unsane (2018)",
    poster: "/3226id.jpg",
    trailer: "https://www.youtube.com/embed/u7KZrt_cHH0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyNTMsMTUyNTQ",
    genre: "Drama | Horror | Mystery | Thriller",
    year: "2018",
    rating: "6.4",
    language: "Hindi",
    description: "একজন নারী নিজের ইচ্ছার বিরুদ্ধে একটি মানসিক চিকিৎসাকেন্দ্রে ভর্তি হয়ে যায়। সেখানে সে বিশ্বাস করতে শুরু করে যে তার অতীতের এক ব্যক্তি তাকে অনুসরণ করছে—কিন্তু সে যা দেখছে, তা সত্যি নাকি তার মানসিক অবস্থার অংশ, সেটাই হয়ে ওঠে বড় রহস্য। 🏥🔍😰",
    views: 23847,
  },
  {
    id: 3227,
    title: "The Exorcism of Hannah Stevenson (2022)",
    poster: "/3227id.jpg",
    trailer: "https://www.youtube.com/embed/Gs7w0UHAbng?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyNTUsMTUyNTY",
    genre: "Horror | Mystery | Thriller",
    year: "2022",
    rating: "4.2",
    language: "Hindi",
    description: "Hannah-এর আচরণ অস্বাভাবিক হয়ে উঠলে তার স্বামী তাকে সাহায্য করার চেষ্টা করে। কিন্তু পরিস্থিতি ক্রমেই ভয়ংকর হয়ে ওঠে এবং তাদের বিশ্বাস ও ভালোবাসার কঠিন পরীক্ষা শুরু হয়। 👻⛪️😨",
    views: 23847,
  },
    {
    id: 3228,
    title: "Call My Agent! The Movie (2026)",
    poster: "/3228id.jpg",
    trailer: "https://www.youtube.com/embed/xByy7zGV8UI?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_Delhi vs Mumbai – Season 1 (2025)",
    genre: "Comedy | Drama | Workplace Drama",
    year: "2026",
    rating: "6.1",
    language: "Hindi",
    description: "সাবেক ট্যালেন্ট এজেন্ট Andréa একজন চলচ্চিত্র পরিচালক হওয়ার চেষ্টা করছে। শুটিং শুরুর মাত্র কয়েক দিন আগে প্রধান অভিনেতা সরে গেলে তাকে পুরোনো টিমকে আবার একত্র করতে হয়। 🎬🎭✨",
    views: 23847,
  },
  {
    id: 3229,
    title: "Delhi vs Mumbai – Season 1 (2025)",
    poster: "/3229id.jpg",
    trailer: "https://www.youtube.com/embed/tGFkVj74UmU?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUyNTksMTUyNjA",
    genre: "Romance | Comedy | Drama | bangla",
    year: "2025",
    rating: "8.3",
    language: "Bangla",
    description: "দিল্লি ও মুম্বাইয়ের দুই ভিন্ন জগতের মানুষের মধ্যে হঠাৎ তৈরি হওয়া সম্পর্ককে ঘিরে গল্প। শহরের সংস্কৃতি, ভুল বোঝাবুঝি ও নানা পরিস্থিতির মধ্য দিয়ে তাদের সম্পর্ক এগিয়ে যায়। ❤️🏙️",
    views: 23847,
  },
    {
    id: 3230,
    title: "Outer Banks – Season 5 (2026)",
    poster: "/3230id.jpg",
    trailer: "https://www.youtube.com/embed/0k0S5G-oq6w?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUyNjEsMTUyODI",
    genre: "Crime | Drama | Mystery | Thriller",
    year: "2026",
    rating: "8.0",
    language: "Hindi",
    description: "Pogues-রা JJ-কে হারানোর পর আবার নিজেদের শহরে ফিরে আসে। অর্থ, ঘরবাড়ি ও Blue Crown হারানোর পাশাপাশি Groff ও নতুন শত্রুদের মোকাবিলা করে তারা বন্ধুর প্রতিশোধ এবং নিজেদের ভবিষ্যৎ ফিরে পাওয়ার জন্য শেষবারের মতো এক বিপজ্জনক অভিযানে নামে। 🌊🏴‍☠️🔍",
    views: 23847,
  },
  {
    id: 3231,
    title: "Ghare and Baire (2018)",
    poster: "/3231id.jpg",
    trailer: "https://www.youtube.com/embed/0k0S5G-oq6w?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUyODMsMTUyODQ",
    genre: "Drama | Romance | bangla",
    year: "2018",
    rating: "6.7",
    language: "Bangla",
    description: "কলকাতার প্রেক্ষাপটে আবর্তিত এই গল্পে একজন নারী ও দুই পুরুষের জটিল সম্পর্কের মধ্য দিয়ে প্রেম, বন্ধুত্ব, মতাদর্শ ও ব্যক্তিগত স্বাধীনতার নানা দিক উঠে আসে। ❤️🏠🌆",
    views: 23847,
  },
    {
    id: 3232,
    title: "Bachelor Point –season 5 Chapter 15 | Episodes 113–120 (2026)",
    poster: "/3232id.jpg",
    trailer: "https://www.youtube.com/embed/0k0S5G-oq6w?si",
    telegramLink: "http://t.me/mvbdstore_bot?start=f_MTUyODUsMTUyODk",
    genre: "Comedy | Drama | bangla",
    year: "2026",
    rating: "8.2",
    language: "Bangla",
    description: "Bachelor House-এর পরিচিত চরিত্রদের জীবনে নতুন নতুন ঘটনা, সম্পর্কের টানাপোড়েন ও মজার পরিস্থিতি তৈরি হতে থাকে। Bachchu Bhai, Pasha, Kabila ও বাকিদের ঘিরে Chapter 15-এ গল্প আরও নতুন দিকে এগিয়ে যায়। 😂🏠❤️",
    views: 23847,
  },
    {
    id: 3233,
    title: "John Wick (2014)",
    poster: "/3233id.jpg",
    trailer: "https://www.youtube.com/embed/C0BMx-qxsP4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyOTIsMTUyOTM",
    genre: "Action | Crime | Thriller",
    year: "2014",
    rating: "7.5",
    language: "Hindi",
    description: "অবসর নেওয়া John Wick-এর অতীত আবার তার জীবনে ফিরে আসে, আর সেখান থেকেই শুরু হয় প্রতিশোধ ও বেঁচে থাকার এক ভয়ংকর যাত্রা। 🔥",
    views: 23847,
  },
  {
    id: 3234,
    title: "John Wick: Chapter 2 (2017)",
    poster: "/3234id.jpg",
    trailer: "https://www.youtube.com/embed/XGk2EfbD_Ps?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyOTQsMTUyOTU",
    genre: "Action | Crime | Thriller",
    year: "2017",
    rating: "7.4",
    language: "Hindi",
    description: "অতীতের একটি ঋণ শোধ করতে গিয়ে John Wick আবার অপরাধজগতের খেলায় ফিরে আসে এবং নিজের জীবনের ওপর নতুন হুমকির মুখোমুখি হয়।",
    views: 23847,
  },
  {
    id: 3235,
    title: "John Wick: Chapter 3 – Parabellum (2019)",
    poster: "/3235id.jpg",
    trailer: "https://www.youtube.com/embed/M7XM597XO94?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyOTYsMTUyOTc",
    genre: "Action | Crime | Thriller",
    year: "2019",
    rating: "7.4",
    language: "Hindi",
    description: "Wick-এর মাথার ওপর বিশাল পুরস্কার ঘোষণা হওয়ার পর বিশ্বজুড়ে শিকারিরা তার পিছু নেয়। পালানোর পাশাপাশি তাকে নিজের বাঁচার পথ খুঁজতে হয়।",
    views: 23847,
  },
  {
    id: 3236,
    title: "John Wick: Chapter 4 (2023)",
    poster: "/3236id.jpg",
    trailer: "https://www.youtube.com/embed/kEvgZCxI3vY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUyOTgsMTUyOTk",
    genre: "Action | Crime | Thriller",
    year: "2023",
    rating: "7.6",
    language: "Hindi",
    description: "High Table-এর বিরুদ্ধে স্বাধীনতা অর্জনের পথ খুঁজে পায় John Wick। কিন্তু সেই পথে তাকে নতুন শক্তিশালী প্রতিপক্ষ ও পুরোনো সম্পর্কের কঠিন পরীক্ষার মুখোমুখি হতে হয়।",
    views: 23847,
  },
  {
    id: 3237,
    title: "Warrior Nun – Season 1 (2020)",
    poster: "/3237id.jpg",
    trailer: "https://www.youtube.com/embed/iEoQKHSfcwc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzMDAsMTUzMjI",
    genre: "Action | Drama | Fantasy | netflix",
    year: "2020",
    rating: "7.0",
    language: "English",
    description: "Ava নামের এক অনাথ কিশোরী হঠাৎ আবিষ্কার করে যে তার মধ্যে বিশেষ ক্ষমতা এসেছে। সে গোপন এক নানদের সংগঠনে যোগ দিয়ে অতিপ্রাকৃত শক্তির বিরুদ্ধে লড়াইয়ের জগতে জড়িয়ে পড়ে। ⚔️✨⚠️Video গুলা অবশ্যই vlc player দিয়ে প্লে করবেন।",
    views: 23847,
  },
  {
    id: 3238,
    title: "Warrior Nun – Season 2 (2022)",
    poster: "/3238id.jpg",
    trailer: "https://www.youtube.com/embed/acdP-NzBhjs?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzMjMsMTUzNDE",
    genre: "Action | Drama | Fantasy | netflix",
    year: "2022",
    rating: "7.0",
    language: "English",
    description: "Ava নামের এক অনাথ কিশোরী হঠাৎ আবিষ্কার করে যে তার মধ্যে বিশেষ ক্ষমতা এসেছে। সে গোপন এক নানদের সংগঠনে যোগ দিয়ে অতিপ্রাকৃত শক্তির বিরুদ্ধে লড়াইয়ের জগতে জড়িয়ে পড়ে। ⚔️✨⚠️Video গুলা অবশ্যই vlc player দিয়ে প্লে করবেন।",
    views: 23847,
  },
  {
    id: 3239,
    title: "A Great Awakening (2026)",
    poster: "/3239id.jpg",
    trailer: "https://www.youtube.com/embed/1cvDtlaIQfA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNDIsMTUzNDM",
    genre: "Drama | History",
    year: "2026",
    rating: "6.6",
    language: "Hindi",
    description: "Reverend George Whitefield ও Benjamin Franklin-এর অপ্রত্যাশিত বন্ধুত্ব এবং আমেরিকার ইতিহাসের এক গুরুত্বপূর্ণ ধর্মীয় জাগরণকে কেন্দ্র করে গল্পটি এগিয়ে যায়। 📖🇺🇸✨",
    views: 23847,
  },
  {
    id: 3240,
    title: "Underworld (2003)",
    poster: "/3240id.jpg",
    trailer: "https://www.youtube.com/embed/2_IoL7g5Ub8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNDQsMTUzNDU",
    genre: "Action | Fantasy | Horror | Thriller",
    year: "2003",
    rating: "7.0",
    language: "Hindi",
    description: "ভ্যাম্পায়ার যোদ্ধা Selene শতাব্দীপ্রাচীন Vampire ও Lycan যুদ্ধের মাঝে পড়ে যায়। এক রহস্যময় ঘটনার পর সে নিজের গোষ্ঠীর বিরুদ্ধেও সত্য অনুসন্ধান করতে শুরু করে। 🧛‍♀️🐺⚔️",
    views: 23847,
  },
  {
    id: 3241,
    title: "Underworld: Evolution (2006)",
    poster: "/3241id.jpg",
    trailer: "https://www.youtube.com/embed/cCtm8L4PQt8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNDYsMTUzNDc",
    genre: "Action | Fantasy | Horror | Thriller",
    year: "2006",
    rating: "6.7",
    language: "Hindi",
    description: "Selene ও Michael তাদের দুই প্রজাতির ইতিহাস এবং দীর্ঘদিনের যুদ্ধের পেছনে থাকা রহস্য উদঘাটনের চেষ্টা করে। 🧛‍♀️🐺🔥",
    views: 23847,
  },
  {
    id: 3242,
    title: "Underworld: Rise of the Lycans (2009)",
    poster: "/3242id.jpg",
    trailer: "https://www.youtube.com/embed/7HCWQjIHJic?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNDgsMTUzNDk",
    genre: "Action | Fantasy | Horror | Thriller",
    year: "2009",
    rating: "6.5",
    language: "Hindi",
    description: "Lycans ও Vampires-এর বহু পুরোনো সংঘাতের শিকড় এবং Lucian-এর নেতৃত্বে Lycan বিদ্রোহের সূচনার গল্প এটি। 🐺⚔️🧛‍♂️",
    views: 23847,
  },
  {
    id: 3243,
    title: "Underworld: Blood Wars (2016)",
    poster: "/3243id.jpg",
    trailer: "https://www.youtube.com/embed/cJ8ao75yQ-w?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNTAsMTUzNTE",
    genre: "Action | Fantasy | Horror | Thriller",
    year: "2016",
    rating: "5.8",
    language: "Hindi",
    description: "Selene Vampire ও Lycan—দুই পক্ষের সংঘাতের মাঝে নিজের অস্তিত্ব ও ভবিষ্যৎ রক্ষার জন্য নতুন যুদ্ধে জড়িয়ে পড়ে। 🧛‍♀️⚔️🐺",
    views: 23847,
  },
  {
    id: 3244,
    title: "The Ledge (2022)",
    poster: "/3244id.jpg",
    trailer: "https://www.youtube.com/embed/xn8Bl-Azmwk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNTIsMTUzNTM",
    genre: "Action | Adventure | Thriller | Survival",
    year: "2022",
    rating: "5.2",
    language: "Hindi",
    description: "পাহাড়ে ওঠার সময় এক তরুণী বিপজ্জনক অবস্থায় আটকা পড়ে এবং কয়েকজন অপরাধীর হাত থেকে নিজেকে রক্ষা করতে মরিয়া হয়ে ওঠে। 🏔️😨🧗‍♀️",
    views: 23847,
  },
  {
    id: 3245,
    title: "Matchless Hero Fang Shiyu (2019)",
    poster: "/3245id.jpg",
    trailer: "https://www.youtube.com/embed/rKj0U2qdFY4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNTQsMTUzNTU",
    genre: "Action | Martial Arts | Historical",
    year: "2019",
    rating: "7.2",
    language: "Chinese",
    description: "কিংবদন্তি মার্শাল আর্ট যোদ্ধা Fang Shiyu-কে ঘিরে প্রতিশোধ, সম্মান ও লড়াইয়ের এক ঐতিহাসিক গল্প। 🥋⚔️",
    views: 23847,
  }, 
  {
    id: 3246,
    title: "Dark (2026)",
    poster: "/3246id.jpg",
    trailer: "https://www.youtube.com/embed/2MfF-_h3fK8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNTYsMTUzNTc",
    genre: "Horror | Mystery | Thriller",
    year: "2026",
    rating: "5.8",
    language: "Hindi",
    description: "এক নাস্তিক ব্যক্তি রহস্যময় অতীতের একটি বাড়িতে বসবাস শুরু করার পর অস্বাভাবিক ঘটনায় জড়িয়ে পড়ে। একটি অপরাধ তাকে অতিপ্রাকৃত শক্তির মুখোমুখি দাঁড় করিয়ে দেয় এবং তার বিশ্বাসকে প্রশ্নের মুখে ফেলে। 🏚️👻🔍",
    views: 23847,
  },
  {
    id: 3247,
    title: "Drinker Sai (2024)",
    poster: "/3247id.jpg",
    trailer: "https://www.youtube.com/embed/cWQflkvQ3fE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNTgsMTUzNTk",
    genre: "Drama | Romance",
    year: "2024",
    rating: "8.7",
    language: "Hindi",
    description: "হৃদয়ভাঙা এক তরুণ নিজের কষ্ট থেকে পালাতে মদ্যপানে ডুবে যায় এবং হারানো ভালোবাসাকে ফিরে পাওয়ার মরিয়া চেষ্টায় নিজের জীবনকে আরও জটিল করে তোলে। 💔🍷🌧️",
    views: 23847,
  },
  {
    id: 3248,
    title: "Tara and Akash: Love Beyond Realms (2025)",
    poster: "/3248id.jpg",
    trailer: "https://www.youtube.com/embed/-HjwtTVHG-8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNjAsMTUzNjE",
    genre:  "Fantasy | Romance | Sci-Fi",
    year: "2025",
    rating: "8.2",
    language: "Hindi",
    description: "সুইজারল্যান্ডে একা ভ্রমণে গিয়ে Tara রহস্যময় Akash-এর সঙ্গে পরিচিত হয়। তাদের সম্পর্ক সময় ও বাস্তবতার সীমা পেরিয়ে এক অসাধারণ প্রেমের গল্পে পরিণত হয়। ❤️✨🏔️",
    views: 23847,
  },
  {
    id: 3249,
    title: "Sultana (2026)",
    poster: "/3249id.jpg",
    trailer: "https://www.youtube.com/embed/ZaUiaGz1V3M?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNjIsMTUzNjM",
    genre: "Drama | Musical",
    year: "2026",
    rating: "7.9",
    language: "Hindi",
    description: "পরিচয়, পরিবার ও জীবনের পরিবর্তনকে ঘিরে এক নারীর আবেগঘন যাত্রার গল্প। 🎭🎶",
    views: 23847,
  },
  {
    id: 3250,
    title: "Mile End Kicks (2026)",
    poster: "/3250id.jpg",
    trailer: "https://www.youtube.com/embed/mzaCmw_VrlI?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNjQsMTUzNjU",
    genre: "Drama | Music",
    year: "2026",
    rating: "5.8",
    language: "Hindi",
    description: "সংগীত, বন্ধুত্ব ও স্বপ্নের জগতে নিজের জায়গা তৈরি করতে চাওয়া এক তরুণের জীবনযাত্রাকে কেন্দ্র করে গল্পটি এগিয়ে যায়। 🎸🎶",
    views: 23847,
  },
  {
    id: 3251,
    title: "The East (2021)",
    poster: "/3251id.jpg",
    trailer: "https://www.youtube.com/embed/kJza8T9_EiE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNjYsMTUzNjc",
    genre: "Drama | War | History",
    year: "2021",
    rating: "6.9",
    language: "Hindi",
    description: "ইন্দোনেশিয়ার স্বাধীনতা-পরবর্তী অস্থির সময়ে এক তরুণ ডাচ সৈনিককে একটি বিশেষ বাহিনীতে পাঠানো হয়। সেখানে সে যুদ্ধ, আনুগত্য ও নৈতিকতার কঠিন বাস্তবতার মুখোমুখি হয়। ⚔️🌏",
    views: 23847,
  },
  {
    id: 3252,
    title: "River God: Water Strange Story (2019)",
    poster: "/3252id.jpg",
    trailer: "https://www.youtube.com/embed/CByX19VOFnY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNjgsMTUzNjk",
    genre: "Fantasy | Mystery | Adventure",
    year: "2019",
    rating: "8.8",
    language: "Hindi",
    description: "রহস্যময় নদী ও অতিপ্রাকৃত ঘটনার পেছনের সত্য অনুসন্ধান করতে গিয়ে একদল মানুষ প্রাচীন কিংবদন্তি ও অজানা শক্তির মুখোমুখি হয়। 🌊🔮",
    views: 23847,
  },
  {
    id: 3253,
    title: "Villains (2019)",
    poster: "/3253id.jpg",
    trailer: "https://www.youtube.com/embed/4-Lc_uHVyE0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNzAsMTUzNzE",
    genre: "Comedy | Horror | Thriller",
    year: "2019",
    rating: "6.3",
    language: "Hindi",
    description: "দুই amateur criminal একটি বাড়িতে ঢুকে পড়ে, কিন্তু সেখানে এমন একটি ভয়ংকর গোপন রহস্য আবিষ্কার করে যা তাদের ধারণারও বাইরে। 🏠😨",
    views: 23847,
  },
  {
    id: 3254,
    title: "Aajo Ardhangini (2026)",
    poster: "/3254id.jpg",
    trailer: "https://www.youtube.com/embed/KSLnrA_1hIY?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNzIsMTUzNzM",
    genre: "Drama | Family | bangla",
    year: "2026",
    rating: "8.4",
    language: "Bangla",
    description: "দুই বছর পর Shubhra একটি বিয়ের অনুষ্ঠানে ফিরে Meghna-র মুখোমুখি হয়। তাদের অতীতের অমীমাংসিত সম্পর্ক ধীরে ধীরে Suman-এর জীবনেও জটিলতা তৈরি করে। 💔🏠",
    views: 23847,
  },
  {
    id: 3255,
    title: "Kiss (2019)",
    poster: "/3255id.jpg",
    trailer: "https://www.youtube.com/embed/CrD7iSUyR7c?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNzQsMTUzNzU",
    genre: "Romance | Drama | Thriller",
    year: "2019",
    rating: "4.9",
    language: "Hindi",
    description: "আধুনিক কলেজছাত্রী Nandini ও ধনী, carefree যুবক Arjun-এর মধ্যে ধীরে ধীরে প্রেমের সম্পর্ক তৈরি হয়। ভিন্ন মূল্যবোধের দুই মানুষের এই সম্পর্ক নানা আবেগ ও পরীক্ষার মুখোমুখি হয়। ❤️🎓",
    views: 23847,
  },
  {
    id: 3256,
    title: "Vidhrohi (2025)",
    poster: "/3256id.jpg",
    trailer: "https://www.youtube.com/embed/C6-9EqXiHX8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNzYsMTUzNzc",
    genre: "Crime | Drama | Mystery | Thriller",
    year: "2025",
    rating: "9.4",
    language: "Hindi",
    description: "পুলিশ কর্মকর্তা Karthik রহস্যময় ধারাবাহিক অপরাধের তদন্ত করতে গিয়ে এক বিপজ্জনক ঘটনার জালে জড়িয়ে পড়ে। সত্যের কাছে পৌঁছাতে গিয়ে তার তদন্ত ক্রমেই কঠিন হয়ে ওঠে। 🚔🔍",
    views: 23847,
  },
  {
    id: 3257,
    title: "Modha Rathiri (2026)",
    poster: "/3257id.jpg",
    trailer: "https://www.youtube.com/embed/UrWrvwIRnqk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzNzgsMTUzNzk",
    genre: "Comedy | Drama | netflix",
    year: "2026",
    rating: "8.8",
    language: "Hindi",
    description: "এক অদ্ভুত বিয়ের অনুষ্ঠানে দুই অপরিচিত মানুষের দেখা হয়। এক রাতের মধ্যে একের পর এক মিথ্যা, গোপন কথা ও অপ্রত্যাশিত ঘটনা পুরো পরিস্থিতিকে বিশৃঙ্খল করে তোলে। 💍😂🌙",
    views: 23847,
  },
  {
    id: 3258,
    title: "Katukutu Buro (2026)",
    poster: "/3258id.jpg",
    trailer: "https://www.youtube.com/embed/dimJoLEsX4I?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzODAsMTUzODE",
    genre: "Drama | Comedy | bangla",
    year: "2026",
    rating: "7.6",
    language: "Bangla",
    description: "একটি পরিবারের পুরোনো সম্পর্ক, আবেগ ও দৈনন্দিন জীবনের নানা হাস্যকর পরিস্থিতিকে ঘিরে এগিয়ে যায় গল্পটি। 🏠❤️😂",
    views: 23847,
  },
  {
    id: 3259,
    title: "Heer Sara (2026)",
    poster: "/3259id.jpg",
    trailer: "https://www.youtube.com/embed/yadvpD__ZyM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzODIsMTUzODM",
    genre: "Coming-of-Age | Road Trip | Adventure | Comedy | Drama",
    year: "2026",
    rating: "6.5",
    language: "Hindi",
    description: "দুই নারী মোটরবাইকে করে Pondicherry-এর উদ্দেশ্যে এক দুঃসাহসিক যাত্রায় বের হয়। একজন খুঁজছে হারিয়ে যাওয়া মাকে, অন্যজন নিজের বিয়ের পেছনের সত্য—আর যাত্রাপথে তৈরি হয় বন্ধুত্ব ও আত্ম-অন্বেষণের গল্প। 🏍️🌴❤️",
    views: 23847,
  },
  {
    id: 3260,
    title: "Thudakkam (2026)",
    poster: "/3260id.jpg",
    trailer: "https://www.youtube.com/embed/ivZ2c69D69E?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzODQsMTUzODU",
    genre: "Action | Drama | Thriller",
    year: "2026",
    rating: "6.1",
    language: "Hindi",
    description: "বিপদের মুখে এক তরুণী নিজের সাহস ও দৃঢ়তার সাহায্যে বেঁচে থাকার চেষ্টা করে। তার সিদ্ধান্ত ও অনুসন্ধান তাকে এমন এক পরিস্থিতিতে নিয়ে যায়, যা তার জীবন চিরতরে বদলে দিতে পারে। 🔥🔍",
    views: 23847,
  },
  {
    id: 3261,
    title: "The Bodyguard (2025)",
    poster: "/3261id.jpg",
    trailer: "https://www.youtube.com/embed/PTcYLB9iTgk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzODYsMTUzODc",
    genre: "Action | Thriller | kdrama",
    year: "2025",
    rating: "7.9",
    language: "Hindi",
    description: "একজন দক্ষ দেহরক্ষী গুরুত্বপূর্ণ এক ব্যক্তিকে রক্ষা করার দায়িত্ব নেয়। কিন্তু ষড়যন্ত্র, বিশ্বাসঘাতকতা ও প্রাণঘাতী হামলার মাঝে দায়িত্ব পালন করতে গিয়ে তাকে নিজের অতীতেরও মুখোমুখি হতে হয়। 🛡️🔥🚨",
    views: 23847,
  },
  {
    id: 3262,
    title: "You+Me – Against the World (2026)",
    poster: "/3262id.jpg",
    trailer: "https://www.youtube.com/embed/eW2SYw4Xvog?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzODgsMTUzOTA",
    genre: "Romance | Drama",
    year: "2026",
    rating: "7.3",
    language: "Hindi",
    description: "দুই ভিন্ন জগতের মানুষের মধ্যে গড়ে ওঠা এক ভালোবাসার গল্প, যেখানে সম্পর্কটিকে টিকিয়ে রাখতে তাদের পরিবার, সমাজ ও নানা প্রতিকূলতার বিরুদ্ধে একসঙ্গে লড়াই করতে হয়। ❤️🌍🥀",
    views: 23847,
  },
  {
    id: 3263,
    title: "The Lottery / Chumbak (2018)",
    poster: "/3263id.jpg",
    trailer: "https://www.youtube.com/embed/tFrfknLLAXU?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzOTEsMTUzOTI",
    genre: "Drama | Coming-of-Age",
    year: "2018",
    rating: "7.7",
    language: "Hindi",
    description: "কিশোর বালু নিজের ছোট ব্যবসার স্বপ্ন পূরণ করতে গিয়ে এক অদ্ভুত মানুষের সঙ্গে পরিচিত হয়। এরপর অর্থ, স্বপ্ন ও নৈতিকতার মধ্যে তাকে কঠিন এক সিদ্ধান্ত নিতে হয়। 🧲💭❤️",
    views: 23847,
  },
  {
    id: 3264,
    title: "Chumbak (2026) — Season 1",
    poster: "/3264id.jpg",
    trailer: "https://www.youtube.com/embed/69auJ1F1EsE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUzOTMsMTU0MTE",
    genre: "Comedy | Family | netflix",
    year: "2026",
    rating: "6.3",
    language: "Hindi",
    description: "মুম্বাইয়ের Chumbak Colony-তে থাকা পাঁচ পরিবারের জীবন, সম্পর্ক, হাসি-কান্না ও প্রতিদিনের নানা ঝামেলা নিয়েই এগিয়ে চলে এই পারিবারিক কমেডি সিরিজ। 🏠😂❤️",
    views: 23847,
  },
  {
    id: 3265,
    title: "We Were Liars – Season 1 (2025)",
    poster: "/3265id.jpg",
    trailer: "https://www.youtube.com/embed/C4tbhW2Gyzc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTU0MTIsMTU0MzA",
    genre: "Thriller | Mystery | Drama | Romance | Thriller",
    year: "2025",
    rating: "6.8",
    language: "Hindi",
    description: "১৭ বছর বয়সী Cady একটি রহস্যময় দুর্ঘটনার পর স্মৃতিভ্রংশে ভোগে। এক বছর পর Beechwood Island-এ ফিরে এসে সে তার হারিয়ে যাওয়া স্মৃতি, পরিবার এবং কাছের বন্ধুদের ঘিরে থাকা রহস্যের সত্য খুঁজতে শুরু করে। 🌊🧩💭",
    views: 23847,
  },
  ]
