export const genres = ["অ্যাকশন", "ড্রামা", "কমেডি", "থ্রিলার", "রোমান্স", "সাইন্স ফিকশন", "হরর", "অ্যাডভেঞ্চার"]

export const movies = [
  {
    id: 1,
    title: "Annapurna (2025)",
    poster: "/annapurna2025.jpg",
    trailer: "https://www.youtube.com/embed/gG__pFybD1o",
    telegramLink: "https://t.me/MVPMCC/10",
    genres: ["ড্রামা", "পরিবার"],
    year: 2025,
    rating: 7.5,
    duration: "115 min",
    director: "TBA",
    cast: "Ananya Chatterjee, Ditipriya Roy, Rishav Basu",
    language: "Bengali",
    description: "A family drama exploring relationships and emotions.",
    views: 8934,
    addedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: 2,
    title: "Despatch (2024)",
    poster: "/despatch2024.jpg",
    trailer: "https://www.youtube.com/embed/Gksb881DX1Q",
    telegramLink: "https://t.me/MVPMCC/12",
    genres: ["থ্রিলার", "ড্রামা"],
    year: 2024,
    rating: 7.1,
    duration: "125 min",
    director: "TBA",
    cast: "Manoj Bajpayee, Shahana Goswami",
    language: "Hindi",
    description: "A crime thriller exploring corruption and justice.",
    views: 36721,
    addedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: 3,
    title: "School 2017 (Season 1)",
    poster: "/school2017season1.jpg",
    trailer: "https://www.youtube.com/embed/JV04wyVD1zQ",
    telegramLink: "https://t.me/MVPMCC/14",
    genres: ["কমেডি", "ড্রামা"],
    year: 2017,
    rating: 7.1,
    duration: "50 min",
    director: "TBA",
    cast: "Kim Se-jeong, Kim Jung-hyun, Jang Dong-yoon",
    language: "Korean",
    description: "A school comedy-drama with mystery elements.",
    views: 22567,
    addedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 4,
    title: "Housefull 5 (2025)",
    poster: "/housefull5a2025.jpg",
    trailer: "https://www.youtube.com/embed/FIRXq35GeC0",
    telegramLink: "https://t.me/MVPMCC/50",
    genres: ["কমেডি", "রোমান্স"],
    year: 2025,
    rating: 7.2,
    duration: "135 min",
    director: "TBA",
    cast: "Akshay Kumar, Riteish Deshmukh, Pooja Hegde, Kriti Sanon",
    language: "Hindi",
    description: "A comedy-romance adventure with multiple couples.",
    views: 41289,
    addedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: 5,
    title: "Housefull 5B (2025)",
    poster: "/housefull5b2025.jpg",
    trailer: "https://www.youtube.com/embed/NM4mhQhTcdM",
    telegramLink: "https://t.me/MVPMCC/52",
    genres: ["কমেডি", "অ্যাডভেঞ্চার"],
    year: 2025,
    rating: 7.1,
    duration: "140 min",
    director: "TBA",
    cast: "Akshay Kumar, Riteish Deshmukh, Jacqueline Fernandez, Kriti Sanon",
    language: "Hindi",
    description: "A family adventure comedy with hilarious moments.",
    views: 38456,
    addedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 6,
    title: "Jungle (2017)",
    poster: "/jungle2017.jpg",
    trailer: "https://www.youtube.com/embed/RI_Iz3-88Fw",
    telegramLink: "https://t.me/MVPMCC/54",
    genres: ["ড্রামা", "থ্রিলার"],
    year: 2017,
    rating: 6.7,
    duration: "96 min",
    director: "TBA",
    cast: "Daniel Radcliffe, Thomas Kretschmann, Alex Russell",
    language: "English",
    description: "A true story of survival in the Amazon jungle.",
    views: 16723,
    addedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 7,
    title: "Mission: Impossible – The Final Reckoning (2025)",
    poster: "/missionimpossible2025.jpg",
    trailer: "https://www.youtube.com/embed/DXPjju8lrVk",
    telegramLink: "https://t.me/MVPMCC/56",
    genres: ["অ্যাকশন"],
    year: 2025,
    rating: 8.3,
    duration: "160 min",
    director: "TBA",
    cast: "Tom Cruise, Hayley Atwell",
    language: "English",
    description: "The final chapter of the Mission: Impossible saga.",
    views: 15420,
    addedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 8,
    title: "The Shawshank Redemption (1994)",
    poster: "/theshawshankredemption1994.jpg",
    trailer: "https://www.youtube.com/embed/d-BICP_lflI",
    telegramLink: "https://t.me/MVPMCC/58",
    genres: ["ড্রামা"],
    year: 1994,
    rating: 9.3,
    duration: "142 min",
    director: "TBA",
    cast: "Tim Robbins, Morgan Freeman, Bob Gunton",
    language: "English",
    description: "A masterpiece about hope and redemption in prison.",
    views: 15420,
    addedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 9,
    title: "Train to Busan 2: Peninsula (2020)",
    poster: "/traintobusan2peninsula.jpg",
    trailer: "https://www.youtube.com/embed/Y-lr2vNTPD0",
    telegramLink: "https://t.me/MVPMCC/61",
    genres: ["অ্যাকশন", "হরর"],
    year: 2020,
    rating: 5.5,
    duration: "116 min",
    director: "TBA",
    cast: "Gang Dong-won, Lee Jung-hyun, Lee Re",
    language: "Korean",
    description: "A zombie apocalypse continues in the Korean peninsula.",
    views: 15420,
    addedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 10,
    title: "Kingdom (2025)",
    poster: "/kingdom2025.jpg",
    trailer: "https://www.youtube.com/embed/OXlaPbKxlEU",
    telegramLink: "https://t.me/MVBDN/64",
    genres: ["অ্যাকশন", "ড্রামা"],
    year: 2025,
    rating: 7.8,
    duration: "50 min",
    director: "TBA",
    cast: "TBA",
    language: "Korean",
    description: "An epic fantasy action series.",
    views: 15420,
    addedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    id: 11,
    title: "Welcome to Waikiki (Season 1)",
    poster: "/256id.jpg",
    trailer: "https://www.youtube.com/embed/4JYuWivKmWw?si",
    telegramLink: "https://t.me/MVPMCC/1299",
    genres: ["কমেডি", "রোমান্স"],
    year: 2018,
    rating: 8.2,
    duration: "60 min",
    director: "Lee Jae-kyoo",
    cast: "Kim Rae-won, Lee Sang-hee",
    language: "Korean",
    description: "A comedy about three men running a guesthouse in Waikiki.",
    views: 45355,
    addedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: 12,
    title: "Bloodhounds (2023)",
    poster: "/250id.jpeg",
    trailer: "https://www.youtube.com/embed/HbYtjXMIxVc?si",
    telegramLink: "https://t.me/MVPMCC/1203",
    genre: "action", "thriler",
    year: 2023,
    rating: 8.1,
    language: "Korean",
    description: "Two young men seek revenge against loan sharks.",
    views: 31672,
  },
  {
    id: 13,
    title: "Study Group (2025)",
    poster: "/195id.jpg",
    trailer: "https://www.youtube.com/embed/QDrEYtI2Ti0?si",
    telegramLink: "https://t.me/MVPMCC/828",
    genres: ["কমেডি", "ড্রামা"],
    year: 2025,
    rating: 8.3,
    duration: "45 min",
    director: "TBA",
    cast: "Kim Se-jeong, Kim Jung-hyun",
    language: "Korean",
    description: "A group of students navigate life and relationships.",
    views: 13445,
    addedAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 14,
    title: "Beyond the Bar (2025)",
    poster: "/183id.jpg",
    trailer: "https://www.youtube.com/embed/FFcsDXwGNNQ?si",
    telegramLink: "https://t.me/MVPMCC/701",
    genres: ["সাইন্স ফিকশন", "ড্রামা"],
    year: 2025,
    rating: 5.8,
    duration: "55 min",
    director: "TBA",
    cast: "TBA",
    language: "Korean",
    description: "A sci-fi drama exploring futuristic themes.",
    views: 9847,
    addedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: 15,
    title: "ROBINHOOD (2025)",
    poster: "/robinhood2025.jpg",
    trailer: "https://www.youtube.com/embed/WxY6LFjWIh4",
    telegramLink: "https://t.me/MVPMCC/175",
    genres: ["অ্যাকশন"],
    year: 2025,
    rating: 8.5,
    duration: "130 min",
    director: "TBA",
    cast: "TBA",
    language: "Hindi",
    description: "A thrilling action-packed journey of modern-day Robinhood.",
    views: 52134,
    addedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: 16,
    title: "Potu (2024)",
    poster: "/potu2024.jpg",
    trailer: "https://www.youtube.com/embed/jnUJJXENykk",
    telegramLink: "https://t.me/MVPMCC/173",
    genres: ["থ্রিলার", "ড্রামা"],
    year: 2024,
    rating: 7.0,
    duration: "110 min",
    director: "TBA",
    cast: "TBA",
    language: "Bengali",
    description: "A gripping thriller from Jaaz Multimedia.",
    views: 27891,
    addedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
  },
  {
    id: 17,
    title: "Saiyaara (2025)",
    poster: "/saiyaara2025.jpg",
    trailer: "https://www.youtube.com/embed/BSJa1UytM8w",
    telegramLink: "https://t.me/MVPMCC/2194",
    genres: ["রোমান্স", "ড্রামা"],
    year: 2025,
    rating: 7.3,
    duration: "140 min",
    director: "TBA",
    cast: "TBA",
    language: "Hindi",
    description: "Love that lives in memory - a romantic musical drama.",
    views: 19456,
    addedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: 18,
    title: "Ekannoborti (2021)",
    poster: "/ekannoborti2021.jpg",
    trailer: "https://www.youtube.com/embed/HsA66Jf3IzI",
    telegramLink: "https://t.me/MVPMCC/8",
    genres: ["ড্রামা"],
    year: 2021,
    rating: 6.7,
    duration: "120 min",
    director: "TBA",
    cast: "Aparajita Adhya, Alokananda Roy",
    language: "Bengali",
    description: "A family drama exploring relationships and emotions.",
    views: 14782,
    addedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
  {
    id: 19,
    title: "Chirodini Tumi je Amar (2008)",
    poster: "/chirodinitumijeamar2008.jpg",
    trailer: "https://www.youtube.com/embed/yyfEIkl1Qww",
    telegramLink: "https://t.me/MVPMCC/63",
    genres: ["রোমান্স", "ড্রামা"],
    year: 2008,
    rating: 7.2,
    duration: "130 min",
    director: "Srijit Mukherji",
    cast: "Rahul Banerjee, Priyanka Sarkar",
    language: "Bengali",
    description: "A romantic drama exploring love and relationships.",
    views: 15420,
    addedAt: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000),
  },
  {
    id: 20,
    title: "Girls will be Girls (2024)",
    poster: "/girlswillbegirls2024.jpg",
    trailer: "https://www.youtube.com/embed/6Z_EXzz_RVk",
    telegramLink: "https://t.me/MVPMCC/65",
    genres: ["ড্রামা"],
    year: 2024,
    rating: 7.5,
    duration: "105 min",
    director: "Shashank Khaitan",
    cast: "Preeti Panigrahi, Kani Kusruti",
    language: "Hindi",
    description: "A coming-of-age drama about friendship and identity.",
    views: 15420,
    addedAt: new Date(Date.now() - 38 * 24 * 60 * 60 * 1000),
  },
]

// Generate additional movies to reach 30+ per page
for (let i = 11; i <= 100; i++) {
  movies.push({
    id: i,
    title: `Movie ${i} (2024)`,
    poster: `/movie${i}.jpg`,
    trailer: `https://www.youtube.com/embed/dQw4w9WgXcQ`,
    telegramLink: `https://t.me/MVPMCC/${i}`,
    genres: [genres[Math.floor(Math.random() * genres.length)]],
    year: 2024,
    rating: Math.round((Math.random() * 4 + 5) * 10) / 10,
    duration: `${90 + Math.floor(Math.random() * 60)} min`,
    director: `Director ${i}`,
    cast: `Actor ${i}, Actress ${i}`,
    language: "Hindi",
    description: `An exciting movie with great entertainment value.`,
    views: Math.floor(Math.random() * 50000),
    addedAt: new Date(Date.now() - Math.floor(Math.random() * 60) * 24 * 60 * 60 * 1000),
  })
}
