export const genres = ["অ্যাকশন", "ড্রামা", "কমেডি", "থ্রিলার", "রোমান্স", "সাইন্স ফিকশন", "হরর", "অ্যাডভেঞ্চার"]

export const movies = [
  {
    id: 1,
    title: "ঢাকা ১৯৭১",
    poster: "/bangladeshi-war-drama-movie-poster.jpg",
    year: 2017,
    rating: 8.2,
    description: "মুক্তিযুদ্ধের সময় ঢাকায় একটি পরিবারের সংগ্রাম এবং বীরত্বের গল্প।",
    genres: ["ড্রামা", "অ্যাকশন"],
    duration: 145,
    director: "মোস্তফা মনোয়ার",
    cast: ["আরমান পারভেজ মুখী", "নাজরুল ইসলাম", "সুমাইয়া শিমু"],
  },
  {
    id: 2,
    title: "চেহারা",
    poster: "/bengali-thriller-movie-poster.jpg",
    year: 2014,
    rating: 7.8,
    description: "একটি রহস্যময় হত্যাকাণ্ড এবং তার সমাধানের গল্প।",
    genres: ["থ্রিলার", "ড্রামা"],
    duration: 128,
    director: "শাশ্বত চট্টোপাধ্যায়",
    cast: ["প্রসেনজিৎ চ্যাটার্জি", "রিধি সেন", "পার্থ বন্দ্যোপাধ্যায়"],
  },
  {
    id: 3,
    title: "আমার বন্ধু রাধা",
    poster: "/bengali-comedy-movie-poster.jpg",
    year: 2016,
    rating: 7.5,
    description: "দুই বন্ধুর মধ্যে প্রেম এবং বন্ধুত্বের সংঘাত।",
    genres: ["কমেডি", "রোমান্স"],
    duration: 115,
    director: "সুজয় প্রসাদ চট্টোপাধ্যায়",
    cast: ["দেব", "সুজয় প্রসাদ চট্টোপাধ্যায়", "পায়েল সরকার"],
  },
  {
    id: 4,
    title: "শাহেদ",
    poster: "/bangladeshi-action-movie-poster.jpg",
    year: 2018,
    rating: 8.0,
    description: "একজন সাহসী পুলিশ অফিসারের অপরাধ দমনের যাত্রা।",
    genres: ["অ্যাকশন", "ড্রামা"],
    duration: 135,
    director: "আবু সিদ্দিক",
    cast: ["শাকিব আল হাসান", "নাজরুল ইসলাম", "সুমাইয়া শিমু"],
  },
  {
    id: 5,
    title: "ভালোবাসার গল্প",
    poster: "/bengali-romance-movie-poster.jpg",
    year: 2015,
    rating: 7.3,
    description: "দুই তরুণের প্রেমের যাত্রা এবং তাদের পরিবারের বাধা।",
    genres: ["রোমান্স", "ড্রামা"],
    duration: 120,
    director: "সুজয় প্রসাদ চট্টোপাধ্যায়",
    cast: ["দেব", "পায়েল সরকার", "রিধি সেন"],
  },
  {
    id: 6,
    title: "রাত্রিকালীন ভয়",
    poster: "/bengali-horror-movie-poster.jpg",
    year: 2017,
    rating: 6.8,
    description: "একটি পরিত্যক্ত বাড়িতে ঘটা রহস্যময় ঘটনা।",
    genres: ["হরর", "থ্রিলার"],
    duration: 110,
    director: "শাশ্বত চট্টোপাধ্যায়",
    cast: ["প্রসেনজিৎ চ্যাটার্জি", "রিধি সেন", "পার্থ বন্দ্যোপাধ্যায়"],
  },
  {
    id: 7,
    title: "অ্যাডভেঞ্চার ইন দ্য জঙ্গেল",
    poster: "/adventure-jungle-movie-poster.jpg",
    year: 2019,
    rating: 7.6,
    description: "জঙ্গলে হারিয়ে যাওয়া একটি দলের বেঁচে থাকার গল্প।",
    genres: ["অ্যাডভেঞ্চার", "অ্যাকশন"],
    duration: 140,
    director: "মোস্তফা মনোয়ার",
    cast: ["শাকিব আল হাসান", "নাজরুল ইসলাম", "সুমাইয়া শিমু"],
  },
  {
    id: 8,
    title: "ভবিষ্যতের স্বপ্ন",
    poster: "/sci-fi-future-movie-poster.jpg",
    year: 2020,
    rating: 8.1,
    description: "ভবিষ্যতের একটি পৃথিবীতে মানুষের সংগ্রাম এবং আশা।",
    genres: ["সাইন্স ফিকশন", "ড্রামা"],
    duration: 150,
    director: "আবু সিদ্দিক",
    cast: ["দেব", "পায়েল সরকার", "রিধি সেন"],
  },
  {
    id: 9,
    title: "হাসির রাজ্য",
    poster: "/bengali-comedy-funny-movie-poster.jpg",
    year: 2018,
    rating: 7.4,
    description: "একটি ছোট শহরে তিন বন্ধুর মজার এবং হাস্যরস অভিযান।",
    genres: ["কমেডি", "অ্যাডভেঞ্চার"],
    duration: 125,
    director: "সুজয় প্রসাদ চট্টোপাধ্যায়",
    cast: ["দেব", "শাকিব আল হাসান", "নাজরুল ইসলাম"],
  },
  {
    id: 10,
    title: "প্রেমের পরিণতি",
    poster: "/bengali-romance-drama-movie-poster.jpg",
    year: 2016,
    rating: 7.7,
    description: "দীর্ঘ প্রেমের সম্পর্কের চূড়ান্ত পরিণতি।",
    genres: ["রোমান্স", "ড্রামা"],
    duration: 130,
    director: "শাশ্বত চট্টোপাধ্যায়",
    cast: ["প্রসেনজিৎ চ্যাটার্জি", "রিধি সেন", "পায়েল সরকার"],
  },
  // Add more movies to reach 50+ for pagination
  ...Array.from({ length: 40 }, (_, i) => ({
    id: 11 + i,
    title: `মুভি ${11 + i}`,
    poster: `/placeholder.svg?height=400&width=300&query=movie-poster-${11 + i}`,
    year: 2015 + (i % 8),
    rating: 6.5 + (i % 30) / 10,
    description: `এটি একটি দুর্দান্ত মুভি যা আপনার মনোযোগ আকর্ষণ করবে।`,
    genres: [genres[i % genres.length], genres[(i + 1) % genres.length]],
    duration: 100 + (i % 60),
    director: `পরিচালক ${i}`,
    cast: [`অভিনেতা ${i}`, `অভিনেতা ${i + 1}`, `অভিনেতা ${i + 2}`],
  })),
]
