export const movies4 = [

{
    id: 3105,
    title: "The Madness (2024) – Season 1",
    poster: "/3105id.jpg",
    trailer: "https://www.youtube.com/embed/gLY42ueSSD8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4MTAsMTQ4Mjg",
    genre: "Thriller | Mystery | Crime | Drama",
    year: "2024",
    rating: "6.5",
    language: "Hindi",
    description: "এক মিডিয়া বিশ্লেষক একটি ভয়ংকর হত্যাকাণ্ডের পর ষড়যন্ত্রের জালে জড়িয়ে পড়ে। নিজের নির্দোষিতা প্রমাণ করতে গিয়ে তাকে পালাতে পালাতে এক ভয়ংকর সত্যের সন্ধান করতে হয়।",
    views: 23847,
  },
  {
    id: 3106,
    title: "Countdown Season 1 (2025)",
    poster: "/3106id.jpg",
    trailer: "https://www.youtube.com/embed/FCBDuQhkx2A?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4MjksMTQ4NTc",
    genre: "Action | Thriller | Drama",
    year: "2025",
    rating: "6.8",
    language: "Hindi",
    description: "এক ভয়ংকর হুমকির বিরুদ্ধে সময়ের সঙ্গে পাল্লা দিয়ে একদল মানুষকে গুরুত্বপূর্ণ রহস্য উন্মোচন করতে হয়। সময় শেষ হওয়ার আগেই তাদের জীবন বাঁচানোর লড়াই শুরু হয়।",
    views: 23847,
  },
  {
    id: 3107,
    title: "The Nightwatchman – Season 1 (2019)",
    poster: "/3107id.jpg",
    trailer: "https://www.youtube.com/embed/CRk2EnxaREA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NTgsMTQ4NzI",
    genre: "Crime | Thriller | Drama | bangla",
    year: "2019",
    rating: "4.6",
    language: "Bangla",
    description: "এক তরুণ আকর্ষণীয় বেতনের চাকরির প্রস্তাব পেয়ে রাতের পাহারাদারের কাজ শুরু করে। কিন্তু চাকরিটির পেছনে লুকিয়ে থাকা অন্ধকার রহস্য ধীরে ধীরে তার জীবনকে বিপদের দিকে ঠেলে দেয়।" ,
    views: 23847,
  },
  {
    id: 3108,
    title: "The Thieves (2012)",
    poster: "/3108id.jpg",
    trailer: "https://www.youtube.com/embed/28qTsiPhYCI?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzMsMTQ4NzQ",
    genre: "Action | Crime | Thriller | Comedy",
    year: "2012",
    rating: "6.8",
    language: "Hindi",
    description: "দক্ষিণ কোরিয়া ও চীনের একদল দক্ষ চোর একটি মূল্যবান হীরার হার চুরি করতে একত্রিত হয়। কিন্তু প্রত্যেকের নিজস্ব পরিকল্পনা থাকায় বিশাল চুরির মিশনটি ধীরে ধীরে বিশ্বাসঘাতকতা ও বিপদের খেলায় পরিণত হয়।",
    views: 23847,
  },
  {
    id: 3109,
    title: "Surrender (2025)",
    poster: "/3109id.jpg",
    trailer: "https://www.youtube.com/embed/GNPkKsV5f34?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzUsMTQ4NzY",
    genre: "Thriller | Drama",
    year: "2025",
    rating: "6.5",
    language: "Hindi",
    description: "এক ভয়ংকর পরিস্থিতিতে আটকে পড়া এক ব্যক্তি বাঁচার জন্য কঠিন সিদ্ধান্ত নিতে বাধ্য হয়। সময়ের সঙ্গে পরিস্থিতি আরও জটিল হয়ে উঠলে সত্য ও বিশ্বাসের পরীক্ষা শুরু হয়।",
    views: 23847,
  },
  {
    id: 3110,
    title: "Cassette 2 (2026)",
    poster: "/3110id.jpg",
    trailer: "https://www.youtube.com/embed/JU-E08zTOlk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzcsMTQ4Nzg",
    genre: "Drama | Thriller | Mystery",
    year: "2026",
    rating: "7.3",
    language: "Hindi",
    description: "একটি রহস্যময় ক্যাসেট ঘিরে পুরোনো কিছু ঘটনা ও গোপন সত্য ধীরে ধীরে সামনে আসে। সত্য উদঘাটনের চেষ্টা করতে গিয়ে চরিত্রগুলো আরও গভীর রহস্য ও বিপদের মধ্যে জড়িয়ে পড়ে।",
    views: 23847,
  },
  {
    id: 3111,
    title: "Hawa Bodol (2013)",
    poster: "/3111id.jpg",
    trailer: "https://www.youtube.com/embed/G22ivKXtRvg?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4NzksMTQ4ODA",
    genre: "Comedy | Drama | Fantasy | bangla",
    year: "2013",
    rating: "7.1",
    language: "Bangla",
    description: "দুই ভিন্ন স্বভাবের মানুষের জীবন হঠাৎ বদলে গেলে তারা একে অপরের জীবনযাপন করতে বাধ্য হয়। এই অদ্ভুত পরিস্থিতি থেকেই তৈরি হয় হাস্যরস, আবেগ ও জীবনের নতুন উপলব্ধির গল্প।",
    views: 23847,
  },
  {
    id: 3112,
    title: "Bonyo Premer Golpo (2020)",
    poster: "/3112id.jpg",
    trailer: "https://www.youtube.com/embed/UVvaSXbTO04?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4ODEsMTQ4OTc",
    genre: "Romance | Drama | bangla",
    year: "2020",
    rating: "6.5",
    language: "Bangla",
    description: "অপরাধজগতের ক্ষমতা ও আধিপত্যের লড়াইকে কেন্দ্র করে এক গ্যাংস্টারের উত্থান ও সংঘর্ষের গল্প। প্রতিশোধ, বিশ্বাসঘাতকতা ও অ্যাকশনে ভরা এই কাহিনিতে ক্ষমতার জন্য শুরু হয় ভয়ংকর লড়াই। 🔥🔫⚔️",
    views: 23847,
  },
  {
    id: 3113,
    title: "Frankenstein's Bride (2026)",
    poster: "/3113id.jpg",
    trailer: "https://www.youtube.com/embed/mSC4pRodc2Y?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ4OTgsMTQ4OTk",
    genre: "Horror | Sci-Fi | Drama",
    year: "2026",
    rating: "7.1",
    language: "Hindi",
    description: "ভিক্টর ফ্রাঙ্কেনস্টাইন তার সৃষ্ট প্রাণীর জন্য এক সঙ্গী তৈরি করতে চায়। কিন্তু নতুন সৃষ্টির আগমন থেকেই শুরু হয় ভালোবাসা, অস্তিত্ব ও নিয়ন্ত্রণকে ঘিরে ভয়ংকর এক সংঘাত।",
    views: 23847,
  },
  {
    id: 3114,
    title: "Resident Playbook (2025) – Season 1",
    poster: "/3114id.jpg",
    trailer: "https://www.youtube.com/embed/sWtOe9DIK9o?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5MDAsMTQ5MjY",
    genre: "kdrama | Medical | Drama | Comedy",
    year: "2025",
    rating: "8.0",
    language: "English",
    description: "ইউলজে মেডিকেল সেন্টারের নতুন OB-GYN রেসিডেন্টরা কঠিন চিকিৎসা-জীবন, রোগী সামলানো ও ব্যক্তিগত সমস্যার সঙ্গে লড়াই করতে করতে দক্ষ ডাক্তার হয়ে ওঠার চেষ্টা করে।",
    views: 23847,
  },
  {
    id: 3115,
    title: "Saas Bahu Achaar Pvt. Ltd. (2022) – Season 1",
    poster: "/3115id.jpg",
    trailer: "https://www.youtube.com/embed/QjcYGkEMuj4?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5MjcsMTQ5NDE",
    genre: "Drama | Family",
    year: "2022",
    rating: "8.2",
    language: "Hindi",
    description: "স্বামীকে ছেড়ে সন্তানদের ফিরে পাওয়ার আশায় সুমন নিজের আচার ব্যবসা শুরু করে। নানা বাধা পেরিয়ে নিজের পায়ে দাঁড়িয়ে নতুন জীবন গড়ার লড়াই শুরু হয় তার।",
    views: 23847,
  },
  {
    id: 3116,
    title: "Monster Island (2024)",
    poster: "/3116id.jpg",
    trailer: "https://www.youtube.com/embed/O-XgvNtiNIE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDIsMTQ5NDM",
    genre: "Horror | Fantasy | Action | Thriller",
    year: "2024",
    rating: "5.2",
    language: "Hindi",
    description: "দ্বিতীয় বিশ্বযুদ্ধের সময় এক জাপানি সৈনিক ও এক ব্রিটিশ যুদ্ধবন্দী নির্জন দ্বীপে আটকা পড়ে। শত্রুতা ভুলে তাদের একসঙ্গে লড়তে হয় ভয়ংকর এক দানবের হাত থেকে বাঁচার জন্য।",
    views: 23847,
  },
  {
    id: 3117,
    title: "Tarikh (2019)",
    poster: "/3117id.jpg",
    trailer: "https://www.youtube.com/embed/4Z6iCxKUaSM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDQsMTQ5NDU",
    genre: "Action | Thriller | bangla",
    year: "2019",
    rating: "6.6",
    language: "Bangla",
    description: "তিন বন্ধুর জীবনে মৃত্যু, সম্পর্ক ও বিশ্বাসের টানাপোড়েন তাদের জীবনকে নতুনভাবে ভাবতে বাধ্য করে। জীবনের প্রতিটি মুহূর্তের মূল্য আর মানুষের অস্তিত্বের অর্থ নিয়েই এগিয়ে যায় গল্পটি।",
    views: 23847,
  },
  {
    id: 3118,
    title: "P Se Pyaar F Se Faraar (2019)",
    poster: "/3118id.jpg",
    trailer: "https://www.youtube.com/embed/ipMd5SSuxbE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDYsMTQ5NDc",
    genre: "Crime | Drama | Romance",
    year: "2019",
    rating: "5.2",
    language: "Hindi",
    description: "ভিন্ন সামাজিক অবস্থানের দুই তরুণ-তরুণী প্রেম করে পালিয়ে বিয়ে করলে তাদের জীবন ভয়ংকর সামাজিক প্রতিশোধ ও সম্মান হত্যার হুমকির মুখে পড়ে।",
    views: 23847,
  },
  {
    id: 3119,
    title: "Raakaasa (2026)",
    poster: "/3119id.jpg",
    trailer: "https://www.youtube.com/embed/TJ5dpuZ1cAk?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NDgsMTQ5NDk",
    genre: "Comedy | Fantasy | Horror | Mystery | bangla",
    year: "2026",
    rating: "6.7",
    language: "Bangla",
    description: "দশ বছর পর আমেরিকা থেকে নিজের গ্রামে ফিরে প্রেমের খোঁজে নামে বীরবাবু। কিন্তু ভুলবশত সে জাগিয়ে তোলে বহুদিনের লুকিয়ে থাকা এক ভয়ংকর প্রাচীন অশুভ শক্তি, যার পরিণতিতে প্রেম পরিণত হয় জীবন-মরণ লড়াইয়ে।",
    views: 23847,
  },
  {
    id: 3120,
    title: "Byomkesh O Agnibaan (2017)",
    poster: "/3120id.jpg",
    trailer: "https://www.youtube.com/embed/Tc9y-8Q4Qik?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTAsMTQ5NTE",
    genre: "Mystery | Thriller | bangla",
    year: "2017",
    rating: "7.1",
    language: "Bangla",
    description: "এক তরুণীর রহস্যময় মৃত্যুর তদন্তে নেমে ব্যোমকেশ এমন এক জটিল রহস্যের মুখোমুখি হয়, যার সঙ্গে প্রতিশোধ ও পুরনো অপরাধের যোগসূত্র রয়েছে।",
    views: 23847,
  },
  {
    id: 3121,
    title: "The Invisible Man (2020)",
    poster: "/3121id.jpg",
    trailer: "https://www.youtube.com/embed/9udDdR4TrmE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTIsMTQ5NTM",
    genre: "Horror | Sci-Fi | Thriller | Mystery",
    year: "2020",
    rating: "7.1",
    language: "Hindi",
    description: "এক নারী তার ভয়ংকর প্রাক্তন প্রেমিকের হাত থেকে পালানোর পর বিশ্বাস করতে শুরু করে যে সে অদৃশ্য হয়ে তাকে অনুসরণ করছে। কিন্তু কেউ তার কথা বিশ্বাস না করায় শুরু হয় বাঁচার এক ভয়ংকর লড়াই।",
    views: 23847,
  },
  {
    id: 3122,
    title: "The Messenger: The Story of Joan of Arc (1999)",
    poster: "/3122id.jpg",
    trailer: "https://www.youtube.com/embed/aCbMOQIs45s?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTQsMTQ5NTU",
    genre: "Biography | Drama | War | History",
    year: "1999",
    rating: "6.4",
    language: "Hindi",
    description: "যুদ্ধবিধ্বস্ত ফ্রান্সে তরুণী জোয়ান অব আর্ক ঈশ্বরের নির্দেশ পাওয়ার দাবি করে ফরাসি সেনাবাহিনীকে নেতৃত্ব দেয়। তার সাহস, বিশ্বাস ও আত্মত্যাগ তাকে ইতিহাসের এক কিংবদন্তি চরিত্রে পরিণত করে।",
    views: 23847,
  },
  {
    id: 3123,
    title: "Widows (2018)",
    poster: "/3123id.jpg",
    trailer: "https://www.youtube.com/embed/nN2yBBSRC78?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTYsMTQ5NTc",
    genre: "Crime | Drama | Thriller",
    year: "2018",
    rating: "6.8",
    language: "Hindi",
    description: "চার বিধবা নারী তাদের মৃত স্বামীদের রেখে যাওয়া ঋণ শোধ করতে এক অসম্ভব ডাকাতির পরিকল্পনা করে। কিন্তু পরিকল্পনা যত এগোয়, তারা ততই জড়িয়ে পড়ে রাজনীতি, অপরাধ আর বিশ্বাসঘাতকতার জালে।",
    views: 23847,
  },
  {
    id: 3124,
    title: "Mirzapur (2026)",
    poster: "/3124id.jpg",
    trailer: "https://www.youtube.com/embed/5vMWZhHPlaw?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NTgsMTQ5NTk",
    genre: "Action | Crime | Thriller | Drama",
    year: "2026",
    rating: "6.7",
    language: "Hindi",
    description: "মির্জাপুরের ক্ষমতা, রাজনীতি ও অপরাধজগতকে ঘিরে এক নতুন গল্প। পুরোনো শত্রুতা, প্রতিশোধ ও ক্ষমতার লড়াইয়ের মাঝে নতুন চরিত্রদের উত্থানে পরিস্থিতি আরও উত্তপ্ত হয়ে ওঠে। 🔥👑⚔️🖤",
    views: 23847,
  },
  {
    id: 3125,
    title: "I'm Game (2026)",
    poster: "/3125id.jpg",
    trailer: "https://www.youtube.com/embed/G2aaDEXNq20?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjAsMTQ5NjE",
    genre: "Thriller | Mystery | Drama",
    year: "2026",
    rating: "7.8",
    language: "Hindi",
    description: "এক রহস্যময় গেমে জড়িয়ে পড়ার পর এক তরুণ বুঝতে পারে, এটি শুধুই বিনোদন নয়। গেমের প্রতিটি ধাপ তাকে নতুন রহস্য ও অপ্রত্যাশিত চ্যালেঞ্জের মুখোমুখি করে। 🎮🔍⚡️",
    views: 23847,
  },
  {
    id: 3126,
    title: "Wolf Pack (2022)",
    poster: "/3126id.jpg",
    trailer: "https://www.youtube.com/embed/mPnTzS-Gkzg?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjIsMTQ5NjM",
    genre: "Action | Thriller | War",
    year: "2022",
    rating: "4.9",
    language: "Hindi",
    description: "বিদেশে নিরাপত্তা মিশনে থাকা Wolf Pack স্কোয়াড আবিষ্কার করে যে সন্ত্রাসী একটি দল চীনের গুরুত্বপূর্ণ জ্বালানি ব্যবস্থায় হামলার পরিকল্পনা করছে। এরপর দেশকে রক্ষা করতে শুরু হয় ভয়ংকর এক মিশন।",
    views: 23847,
  },
  {
    id: 3127,
    title: "jekhane bhuter bhoy (2012)",
    poster: "/3127id.jpg",
    trailer: "https://www.youtube.com/embed/3E8HGhSNEvA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjQsMTQ5NjU",
    genre: "bangla | Horror | Comedy | Mystery",
    year: "2012",
    rating: "7.2",
    language: "Bangla",
    description: "চারটি ভৌতিক গল্পের মাধ্যমে কলকাতার বিভিন্ন জায়গায় ঘটে যাওয়া অদ্ভুত ও রহস্যময় ঘটনার কাহিনি তুলে ধরা হয়েছে। ভয় আর হাসির মিশেলে এগিয়ে যায় চার ভূতের মজার গল্প।",
    views: 23847,
  }, 
  {
    id: 3128,
    title: "Coke / Human Cocaine (2026)",
    poster: "/3128id.jpg",
    trailer: "https://www.youtube.com/embed/XdHH2vDb0SM?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjYsMTQ5Njc",
    genre: "Action | Crime | Thriller",
    year: "2026",
    rating: "5.7",
    language: "Hindi",
    description: "পরিবারকে ফিরে পাওয়ার আশায় ক্যাবচালক অর্জুন একটি লাভজনক ডেলিভারির কাজ নেয়। কিন্তু পথে এক অচেনা যাত্রীকে সাহায্য করতে গিয়ে সে ইউরোপের ভয়ংকর মাদকচক্রের হাতে বন্দি হয়ে যায়।",
    views: 23847,
  },
  {
    id: 3129,
    title: "Kangaroo Kids (2026)",
    poster: "/3129id.jpg",
    trailer: "https://www.youtube.com/embed/WeOHwTVjvVQ?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NjgsMTQ5Njk",
    genre: "Comedy | Drama | Family",
    year: "2026",
    rating: "7.8",
    language: "Hindi",
    description: "কয়েকজন কিশোর-কিশোরীর বন্ধুত্ব, স্কুলজীবন ও নানা মজার ঘটনার মধ্য দিয়ে এগিয়ে চলে গল্প। তাদের দুষ্টুমি, স্বপ্ন ও পারিবারিক সম্পর্ক মিলিয়ে তৈরি হয় আনন্দঘন এক কাহিনি। 🎒😂❤️✨",
    views: 23847,
  },
  {
    id: 3130,
    title: "Star Wars: The Mandalorian and Grogu (2026)",
    poster: "/3130id.jpg",
    trailer: "https://www.youtube.com/embed/ROn_r35ioV8?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzAsMTQ5NzE",
    genre:  "ion | Adventure | Fantasy | Sci-Fi",
    year: "2026",
    rating: "6.8",
    language: "Hindi",
    description: "গ্যালাক্সিতে নতুন বিপদের মুখে ম্যান্ডালোরিয়ান দিন জারিন ও তার শিষ্য গ্রোগু এক দুর্ধর্ষ মিশনে বের হয়। পথে সাম্রাজ্যের অবশিষ্ট শক্তির বিরুদ্ধে লড়াই করতে গিয়ে তাদের বন্ধন ও সাহসের কঠিন পরীক্ষা হয়।",
    views: 23847,
  },
  {
    id: 3131,
    title: "The Runner (2026)",
    poster: "/3131id.jpg",
    trailer: "https://www.youtube.com/embed/nPjcXUYboDE?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzIsMTQ5NzM",
    genre: "Action | Thriller | Drama | Mystery",
    year: "2026",
    rating: "5.9",
    language: "Hindi",
    description: "লন্ডনের আইনজীবী মাইয়ার ছেলেকে অপহরণ করে এক রহস্যময় ব্যক্তি। ছেলেকে বাঁচাতে তাকে শহরজুড়ে দৌড়াতে ও একের পর এক ভয়ংকর নির্দেশ পালন করতে হয়।",
    views: 23847,
  },
  {
    id: 3132,
    title: "The Wrath of God (2022)",
    poster: "/3132id.jpg",
    trailer: "https://www.youtube.com/embed/b6YpZl1gl8s?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzQsMTQ5NzU",
    genre: "Mystery | Thriller | Drama | netflix",
    year: "2022",
    rating: "6.0",
    language: "Hindi",
    description: "এক লেখক তার জীবনে ঘটে যাওয়া একের পর এক রহস্যময় মৃত্যুর পেছনে তার সাবেক বসের হাত রয়েছে বলে সন্দেহ করে। সত্য উদঘাটন করতে গিয়ে সে প্রতিশোধ, ভয় আর অন্ধকার রহস্যের মুখোমুখি হয়।",
    views: 23847,
  },
  {
    id: 3133,
    title: "ISHQ (Don't Fall in Love) (2024)",
    poster: "/3133id.jpg",
    trailer: "https://www.youtube.com/embed/ZO8TkW-vZDs?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzYsMTQ5Nzc",
    genre: "Sci-Fi | Drama | Mystery",
    year: "2024",
    rating: "6.6",
    language: "Hindi",
    description: "বিয়ে ও সম্পর্কের প্রতি আস্থা হারিয়ে রাম সিঙ্গেল থাকার সিদ্ধান্ত নেয়। কিন্তু পরিবারের বিয়ের চাপের মাঝে এক মেয়ের সঙ্গে তার দেখা হলে ভালোবাসা ও জীবনের সিদ্ধান্ত নিয়ে নতুন দ্বন্দ্ব শুরু হয়।",
    views: 23847,
  },
  {
    id: 3134,
    title: "The Legend of ShenLi (2024) – Season 1",
    poster: "/3134id.jpg",
    trailer: "https://www.youtube.com/embed/hC00-C6p5og?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTQ5NzgsMTUwMDA",
    genre: "kdrama | Fantasy | Romance | Action | Historical",
    year: "2024",
    rating: "8.1",
    language: "Hindi",
    description: "ডেমন জগতের শক্তিশালী যোদ্ধা শেন লি পালিয়ে মানবজগতে এসে গুরুতর আহত অবস্থায় এক রহস্যময় পুরুষের সাহায্য পায়। ধীরে ধীরে তাদের মধ্যে প্রেমের জন্ম হলেও অতীতের পরিচয় ও স্বর্গ-দৈত্য জগতের সংঘাত তাদের সম্পর্ককে কঠিন পরীক্ষার মুখে ফেলে।",
    views: 23847,
  },
  {
    id: 3135,
    title: "Gandhari (2026)",
    poster: "/3135id.jpg",
    trailer: "https://www.youtube.com/embed/Cq58YGCO_2c?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDEsMTUwMDI",
    genre: "Action | Crime | Thriller | Mystery | Drama",
    year: "2026",
    rating: "4.8",
    language: "Hindi",
    description: "মেয়েকে অপহরণ করার পর দৃষ্টিশক্তি হারানো মা বাণী নিজেই অপরাধীদের খুঁজে বের করার লড়াইয়ে নামে। মেয়েকে উদ্ধার করতে গিয়ে সে জড়িয়ে পড়ে এক ভয়ংকর অপরাধচক্র ও প্রতিশোধের খেলায়।",
    views: 23847,
  },
  {
    id: 3136,
    title: "Unmadham (2026)",
    poster: "/3136id.jpg",
    trailer: "https://www.youtube.com/embed/zGqJqfr76ao?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDMsMTUwMDQ",
    genre: "Crime | Mystery | Psychological Thriller",
    year: "2026",
    rating: "6.3",
    language: "Hindi",
    description: "অতীতের ভারে জর্জরিত পুলিশ কনস্টেবল শেলি বহুদিনের পুরোনো একটি অমীমাংসিত মামলা আবার খুলে তদন্ত শুরু করে। তদন্ত যত এগোয়, কুসংস্কার, গোপন রহস্য ও অতিপ্রাকৃত ঘটনার মাঝে বাস্তবতা নিয়ে তার বিশ্বাসও প্রশ্নের মুখে পড়ে।",
    views: 23847,
  },
  {
    id: 3137,
    title: "Journey to the West: The Demons Strike Back (2017)",
    poster: "/3137id.jpg",
    trailer: "https://www.youtube.com/embed/PuDEs9_Jsz0?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDUsMTUwMDY",
    genre: "Fantasy | Adventure | Comedy | Action",
    year: "2017",
    rating: "5.4",
    language: "Hindi",
    description: "সান উকং, ঝু বাজিয়ে ও শা উজিংকে নিয়ে তাং সানজাং আবারও বিপজ্জনক এক অভিযানে বের হয়। পথে তারা নানা দানব ও অতিপ্রাকৃত শক্তির মুখোমুখি হয়, আর বুদ্ধি ও শক্তির সাহায্যে তাদের মোকাবিলা করতে থাকে। 🐒⚔️👹",
    views: 23847,
  },
  {
    id: 3138,
    title: "Lovesick – Season 1 (2026)",
    poster: "/3138id.jpg",
    trailer: "https://www.youtube.com/embed/6vorXO9Mc-U?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMDcsMTUwMjM",
    genre: "Romance | History | Drama",
    year: "2026",
    rating: "5.7",
    language: "Hindi",
    description: "মেক্সিকান বিপ্লবের অস্থির সময়ে এমিলিয়া সৌরি সমাজের প্রচলিত বাধা অতিক্রম করে ডাক্তার হওয়ার স্বপ্ন পূরণের চেষ্টা করে। একইসঙ্গে প্রেম, পরিবার, রাজনৈতিক পরিবর্তন ও নিজের স্বাধীনতার জন্য তাকে নানা কঠিন সিদ্ধান্তের মুখোমুখি হতে হয়। ❤️🩺🇲🇽",
    views: 23847,
  },
  {
    id: 3139,
    title: "Khuda Haafiz (2020)",
    poster: "/3139id.jpg",
    trailer: "https://www.youtube.com/embed/q67l_GOUzGc?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMjQsMTUwMjU",
    genre: "Action | Thriller | Drama",
    year: "2020",
    rating: "7.1",
    language: "Hindi",
    description: "সমীর ও নার্গিসের নতুন জীবনের শুরুতেই নার্গিস নিখোঁজ হয়ে যায়। তাকে খুঁজে বের করতে সমীর এক বিপজ্জনক বিদেশি শহরে পাড়ি জমায় এবং অপরাধচক্রের বিরুদ্ধে লড়াইয়ে জড়িয়ে পড়ে। 🔥🔎❤️",
    views: 23847,
  },
  {
    id: 3140,
    title: "Khuda Haafiz Chapter 2: Agni Pariksha (2022)",
    poster: "/3140id.jpg",
    trailer: "https://www.youtube.com/embed/iPaSef3NtMA?si",
    telegramLink: "https://t.me/mvbdstore_bot?start=f_MTUwMjYsMTUwMjc",
    genre: "Action | Thriller | Drama",
    year: "2022",
    rating: "7.0",
    language: "Hindi",
    description: "প্রথম সিনেমার ঘটনার পর সমীর ও নার্গিস তাদের জীবনে নতুনভাবে ঘুরে দাঁড়ানোর চেষ্টা করে। কিন্তু এক মর্মান্তিক ঘটনার পর তাদের জীবন আবারও অন্ধকারে ঢেকে যায়, আর সমীর ন্যায়বিচারের জন্য কঠিন লড়াইয়ে নামতে বাধ্য হয়। ⚔️🔥💔",
    views: 23847,
  }, 
  ]
